react-hook-form/documentation

src/components/ApiFormState.tsx
doc changing according to [pull request](https://github.com/bluebill1049/react-hook-form/pull/89)
=> updated doc for changed formState api

src/components/ApiRefTable.tsx
Fix incorrect example key under register section.
=> Fix register example key

src/components/codeExamples/typeScript.ts
the onSubmit function was wrapped two with`handleSubmit`  times in the typescript example
=> remove duplicate handleSubmit wrapper

src/components/ApiRefTable.tsx
=> fix(docs): update link to array example

gatsby-config.js, package.json, src/components/AdvancedUsage.tsx, src/components/ApiErrors.tsx, src/components/ApiPage.tsx, src/components/ApiRefTable.tsx, src/components/ApiWatch.tsx, src/data/advanced.tsx, src/data/api.tsx, src/data/generic.tsx, src/data/getStarted.tsx, src/data/home.tsx
@bluebill1049 I absolutely love the look of website, but I have felt that the English grammar needs some help :). I hope this helps.  Please run it and let me know if you find any problems or concerns.
Since I may need to reduce my involvement in react-hook-form in the next few weeks, I really wanted to do this to help out.
=> Improve english grammar

src/data/nav.tsx
=> translate api data into japanese

src/data/builder.tsx, src/data/generic.tsx
=> translate form builder data into japanese

src/data/generic.tsx
=> translate form generic data into japanese

src/data/generic.tsx, src/data/getStarted.tsx, src/data/home.tsx
=> translate getStarted data into japanese

src/components/FormContext.tsx, src/components/SideMenu.tsx, src/components/layout.css
I also changed how the `formContext` example looks to apply syntax highlighter.
=> Improve scrollbar

src/data/generic.tsx, src/data/getStarted.tsx
* Translated generic data into Korean
* Translated whole content of 'Get Started' page into Korean
=> Translate 'Get Started' page into Korean

src/data/builder.tsx
=> Translate 'Builder' page into korean

src/data/advanced.tsx, src/data/generic.tsx
I think the [previous PR](https://github.com/react-hook-form/react-hook-form-website/pull/44) should be merged first.
=> translate 'Advanced' page into korean

src/data/faq.tsx, src/data/nav.tsx
No specific description needed.
=> Translate 'FAQs' page into Korean

src/data/api.tsx
=> translate from api data into japanese

src/data/advanced.tsx
=> translate from advanced data into japanese

src/data/faq.tsx
[Reference](https://github.com/react-hook-form/react-hook-form-website/issues/42#issuecomment-547199130)
Updated a new FAQ content for the korean page.
=> translate 'comparison' section into korean

src/components/Nav.tsx, src/data/api.tsx
API page into Korean 🇰🇷 
related issue : https://github.com/react-hook-form/react-hook-form-website/issues/42
=> translated "API" page into Korean

src/data/getStarted.tsx
related: https://github.com/react-hook-form/react-hook-form-website/pull/78
=> translate workWithUI description in getStarted page into japanese

src/data/api.tsx, src/data/getStarted.tsx
* Updated the 'Work with UI Library' section
* Updated the description of `setError` API
* Translated the new `validateCriteriaMode` API
=> Update Korean translations

src/data/api.tsx
- suggested changes to the Optional Chaining / nested error paragraph
=> Update api.tsx text and grammar

src/data/faq.tsx
=> Fix Faq copy

src/components/GetStartedPage.tsx, src/data/getStarted.tsx
Created for https://github.com/react-hook-form/react-hook-form-input/issues/3#issuecomment-558320339
Will need to be translated to `KR`, `JP`, and `ZH`
=> Made workingwithUIlibrary more clear in English

src/data/getStarted.tsx
=> Update getStarted page

src/data/getStarted.tsx
=> Update korean translation of 'Get Started' -> 'UI components'

src/components/FaqPage.tsx
IE11 caused problem with missing find function. With this polyfill, you can get a working version of it.
=> FaqPage.tsx IE11 add polyfill link

src/components/codeExamples/control.ts
The `control` was missing. `register` and `setValue` was destructured for no use. Removed these two, and added control.
=> Import control from useForm()

src/components/ApiPage.tsx, src/components/ErrorMessage.tsx, src/components/SideMenu.tsx, src/data/en/api.tsx, src/data/jp/api.tsx, src/data/kr/api.tsx, src/data/pt/api.tsx, src/data/zh/api.tsx
@kotarella1110 you may want to take the Japanese translation
=> update with error message

src/components/codeExamples/errorMessage.ts
=> chore(docs): fixed minor code typo

src/components/codeExamples/RHFInput.ts, src/components/codeExamples/getStarted.ts, src/data/en/api.tsx, src/data/en/getStarted.tsx
Update controller doc to be more explicit.
(After my great exploration ahah)
=> Update controller doc

src/data/pt/advanced.tsx, src/data/pt/api.tsx, src/data/pt/faq.tsx
Hello, here's the translation needed for V4, Issue #118 
Tell me if anything else is necessary to translate 😄 
Note: This translation V4 is great !!!, congratulations for it, is now much easier to find and manage the i18n.
=> Brazilian translation V4

src/components/ApiFormState.tsx, src/components/ApiPage.tsx
=> Add note for formState.isValid usage with mode

src/components/codeExamples/getStarted.ts
I changed maxlength to maxLength as discussed on spectrum
=> Fixed a casing issue in apply validation example

README.md
Small correction for the broken link :)
=> Become a contributor link lead to 404 error #159

src/components/codeExamples/getStarted.ts
`register={register}` -> `ref={register}`
=> Fix prop name in Adapting existing form code example

src/data/es/api.tsx
Hi @bluebill1049 I updated Fields Arrays translation that you asked for few weeks ago. I was on vacations! Thanks for this great library. Keep moving foward, regggards!
=> Update api.tsx in spanish translation

src/components/codeExamples/useFieldArray.ts
If this is merged, it will fix some layout bugs in the demo of [useFieldArray()](https://react-hook-form.com/advanced-usage#FieldArrays) CONTROLLER tab.
_Thank you for the awesome package ❤️_
=> [bugfix] useFieldArray() > controller demo markup

src/data/home.tsx, src/data/kr/api.tsx
- `validationResolver`, `validationContext`
- Isolate Component Re-render
- `error` object update
=> Korean translation updates

src/components/ErrorMessage.tsx, src/components/codeExamples/errorsMessage.ts, src/data/en/api.tsx, src/data/es/api.tsx, src/data/jp/api.tsx, src/data/kr/api.tsx, src/data/pt/api.tsx, src/data/ru/api.tsx, src/data/zh/api.tsx
related: https://github.com/react-hook-form/react-hook-form/issues/1050
=> add multiple errors example for ErrorMessage component

src/components/ApiRefTable.tsx
related: https://github.com/react-hook-form/react-hook-form/pull/1061
=> add object type to required for register validation rule

src/components/codeExamples/useFieldArray.ts, src/components/codeExamples/useFieldArrayArgument.ts, src/data/en/api.tsx, src/data/jp/api.tsx, src/data/kr/api.tsx, src/data/pt/api.tsx, src/data/ru/api.tsx, src/data/zh/api.tsx
related issue: https://github.com/react-hook-form/react-hook-form/issues/1070
related PR: https://github.com/react-hook-form/react-hook-form/pull/1106
=> improve regsiter in useFieldArray section

src/components/DevTools.tsx, src/components/Form.tsx, src/data/devtools.tsx, src/data/en/devtools.tsx, src/data/es/devtools.tsx, src/data/generic.tsx, src/data/home.tsx, src/data/jp/devtools.tsx, src/data/kr/devtools.tsx, src/data/pt/devtools.tsx, src/data/ru/devtools.tsx, src/data/zh/devtools.tsx, src/pages/dev-tools.es.tsx, src/pages/dev-tools.jp.tsx, src/pages/dev-tools.kr.tsx, src/pages/dev-tools.pt.tsx, src/pages/dev-tools.ru.tsx, src/pages/dev-tools.zh.tsx
@kotarella1110 @adhrinae please help on the translation when you guys have some free time. by the way @adhrinae sorry i have removed that type css module plugin, it didn't solve the problem, instead it create files change each time. I think we can leave with those stupid errors for now.
=> translate dev tool page

src/data/pt/devtools.tsx, src/data/pt/faq.tsx, src/data/pt/getStarted.tsx
Translating dev-tools to PT-Br and fixing some grammar mistakes on the pages previously translated.
=> Translating to pt br

src/components/codeExamples/accessibleCode.ts, src/components/codeExamples/accessibleCodeFinal.ts
=> Update A11y examples

src/data/jp/api.tsx
* update useForm's defaultValues option
* update validationResolver section
* update useFieldArray section
* update Controller onChange prop
* update formState section
=> update api page translated into jp

src/components/codeExamples/reactNativeController.ts
Update example in Controller when used in React native, message prop type invalid prop value, in react-native TextInput value returned by onChange must be a string.
This issue was raised in https://github.com/react-hook-form/react-hook-form/issues/769
=> Update Doc Controller example

src/data/jp/api.tsx
completed: https://github.com/react-hook-form/react-hook-form-website/commit/d730fe15ca405e73d23a4eb7a85c09d4199b7065
=> update validationResolver section in api page translated into jp

src/components/AdvancedPage.tsx, src/components/codeExamples/virtualizedList.ts, src/data/en/advanced.tsx, src/data/en/faq.tsx, src/data/es/advanced.tsx, src/data/jp/advanced.tsx, src/data/kr/advanced.tsx, src/data/pt/advanced.tsx, src/data/ru/advanced.tsx, src/data/zh/advanced.tsx
This is my first time contributing to this project, so let me know what steps I might be missing.
The goal of this PR is to add an example on how RHF could work with a virtualized list (I was using react-window by Brian Vaughn).
I would guess that if accepted, the CodeSandBox example would want to be forked to NOT be under my account.
I have a CodeSandBox showing the issue that I started with:
https://codesandbox.io/s/virtulized-react-hook-form-issue-efynk
and one that has a work around:
https://codesandbox.io/s/virtulized-react-hook-form-fix-o75u2
as well as a simplified workaround without any styles and in a single file:
https://codesandbox.io/s/virtulized-react-hook-form-fix-simple-w38ty
=> example for working with a virtualized list

src/components/ApiPage.tsx, src/components/Controller.tsx, src/components/Header.tsx, src/components/HomePage.tsx, src/data/en/advanced.tsx, src/data/en/api.tsx, src/data/es/advanced.tsx, src/data/es/api.tsx, src/data/jp/advanced.tsx, src/data/jp/api.tsx, src/data/kr/advanced.tsx, src/data/kr/api.tsx, src/data/pt/advanced.tsx, src/data/pt/api.tsx, src/data/ru/advanced.tsx, src/data/ru/api.tsx, src/data/zh/advanced.tsx, src/data/zh/api.tsx
@kotarella1110 @adhrinae please translate the content when you guys have some free times. thank you
=> update content for onFocus for controller

src/components/ApiRefTable.tsx, src/components/Header.module.css, src/data/en/api.tsx, src/data/es/api.tsx, src/data/jp/api.tsx, src/data/kr/api.tsx, src/data/pt/api.tsx, src/data/ru/api.tsx, src/data/zh/api.tsx
close https://github.com/react-hook-form/react-hook-form/issues/1540
=> improve doc

src/components/codeExamples/setError.ts
I've found 'clearError' missed in the example code and i inserted it.
=> Insert 'clearError' method

src/data/en/api.tsx
Fixed version: https://react-hook-form-website-git-fork-andipaetzold-patch-1.bluebill1049.now.sh/api#setValue
=> Fix missing space in useForm -> setValue

src/data/en/advanced.tsx
```diff
You can build a custom hook as a validation resolver. A custom hook
- can easily integration with yup/Joi/Superstruct as a validation
+ can easily integrate with yup/Joi/Superstruct as a validation
method, and to be used inside validation resolver.
```
=> Typo correction

src/data/en/advanced.tsx
Sorry about the first commit, which I had previously submitted via a separate PR. I was editing from GitHub's UI.
=> docs: improve English in Advanced

src/data/en/faq.tsx
Per https://github.com/react-hook-form/react-hook-form/issues/230#issuecomment-522764265
=> Add focus as a ref usage case

src/components/AdvancedPage.tsx
Hello,
This PR is to fix the anchor links on the Advanced Usage page. :)
To be fixed:
* Error Messages
* Working with virtualized lists
Note: The file is automatically formatted based on Husky pre-commit. I didn't do it intentionally.
=> Fixed Side Menu anchor links on Advanced Usage page

src/data/jp/advanced.tsx
I translated Advanced Usage page into jp.
=> Translated  advanced useage page into jp

src/pages/v5/api.en.tsx, src/pages/v5/api.es.tsx, src/pages/v5/api.jp.tsx, src/pages/v5/api.kr.tsx, src/pages/v5/api.pt.tsx, src/pages/v5/api.ru.tsx, src/pages/v5/api.zh.tsx
Sorry, the file path were incorrect on ApiPage.
=> Fixed data path on ApiPage 

src/components/ApiPageV5.tsx, src/pages/v5/api.en.tsx, src/pages/v5/api.es.tsx, src/pages/v5/api.jp.tsx, src/pages/v5/api.kr.tsx, src/pages/v5/api.pt.tsx, src/pages/v5/api.ru.tsx, src/pages/v5/api.zh.tsx
I fixed bugs that data is not loaded.
=> Fixed bugs on ApiPageV5

src/components/FaqPage.tsx, src/pages/faqs.en.tsx, src/pages/faqs.es.tsx, src/pages/faqs.jp.tsx, src/pages/faqs.kr.tsx, src/pages/faqs.pt.tsx, src/pages/faqs.ru.tsx, src/pages/faqs.zh.tsx
I fixed FaqPage perf.
FYI, see the following pictures.
Before:
After:
=> Improved FaqPage bundle size

src/components/DevToolFeaturesList.tsx, src/components/DevTools.tsx, src/pages/dev-tools.en.tsx, src/pages/dev-tools.es.tsx, src/pages/dev-tools.jp.tsx, src/pages/dev-tools.kr.tsx, src/pages/dev-tools.pt.tsx, src/pages/dev-tools.ru.tsx, src/pages/dev-tools.zh.tsx
I fixed file that load data. 
And I split bundle in each languages in DevTool page.
=> Improved performance DevTool page

src/components/ApiPage.tsx, src/components/V5/ApiPageV5.tsx
I Aligned the code on the website with what is in the codesandbox's. 
I am planning on adding some more codesandbox's if this PR is met with approval.
=> Correct V5 & V6 Docs + added ts-codesandbox

src/components/ApiPage.tsx, src/data/en/api.tsx, src/data/es/api.tsx, src/data/jp/api.tsx, src/data/kr/api.tsx, src/data/pt/api.tsx, src/data/ru/api.tsx, src/data/zh/api.tsx
Added option ```all``` to useForm Documentation.
Note: I used google translate for all translations (excluding english).
Doing my part to help get V6 out into the world! 😸
=> Add all to useForm mode Documentation

src/data/home.tsx
=> Translate spanish

src/components/HomePage.tsx, src/components/Watcher.tsx, src/data/home.tsx
I supported i18n in SubScribe Input Change section.
And I translated to jp.
=> Support i18n in Subscribe Input Change section in Home

src/data/en/faq.tsx, src/data/jp/faq.tsx, src/data/pt/faq.tsx
- I fixed typo
- I translated to jp
=> Translated to jp in FAQs page

src/components/ApiPage.tsx, src/components/CodeArea.tsx, src/components/V5/ApiPageV5.tsx, src/components/ValidationResolver.tsx, src/components/codeExamples/validationResolver.ts, src/components/codeExamples/validationResolverTs.tsx
- make it possible to click `copy` to copy TS code.
- clearly separate v5 and v6 sandbox's
- fix and update the custom validation resolver codesandbox's and displayed code
=> Small Bug Fix and CodeSandbox v5/v6 seperation

src/data/es/advanced.tsx
=> [updated] review advanced page

src/components/ApiWatch.tsx, src/components/codeExamples/watchCode.ts
Title Says it all:
- Add TS and improved JS CodeExample
- Improve Code Example.
=> Add Code Example and Correct Code for useForm Watch 

src/components/CodeArea.tsx
- removes lodash/fp (and lodash entirely) string === string
- add logic to handle just (ss & types) or just (types and js)
=> remove lodash from codeArea & enhance logic

src/components/ApiPage.tsx, src/components/ApiWatch.tsx, src/components/CodeArea.tsx, src/components/codeExamples/watchCode.ts, src/components/codeExamples/watchCodeTs.ts, src/components/codeExamples/watchCodeTypes.ts
Title says it all
- Added CodeExamples
- Added TS code and Types button
=> Update watch CodeExample + TS Code

src/components/ApiPage.tsx, src/components/CodeArea.tsx, src/components/codeExamples/resetCodeTs.ts
Title Says it all
- Added CodeSandbox
- Added TS Code
=> Added Reset Example and CodeSandbox

src/components/ApiPage.tsx, src/components/CodeArea.tsx, src/components/codeExamples/resetCodeTs.ts, src/components/codeExamples/setAllErrorsTs.ts, src/components/codeExamples/setErrorTs.ts, src/components/codeExamples/setMultipleErrorsTs.ts, src/data/en/api.tsx
- Use best practice ```type``` variable for the first TS example 
- Fix some english issues
- Simplify setError Code Examples
- Create setError TS Code Examples
- Build a large inclusive CodeSandbox for both Ts and JS
- Both CodeSandbox's have examples for three setError use cases
=> Expand/improve setError Docs

src/components/AdvancedPage.tsx, src/components/codeExamples/testingForm.ts, src/data/en/advanced.tsx, src/data/es/advanced.tsx, src/data/jp/advanced.tsx, src/data/kr/advanced.tsx, src/data/pt/advanced.tsx, src/data/ru/advanced.tsx, src/data/zh/advanced.tsx
=> Added test tutorial

src/components/ApiPage.tsx, src/components/CodeArea.tsx, src/components/codeExamples/clearErrorTs.ts
- add TS and JS code example and sandbox to clearError Docs
- fix CodeArea bug that would show CodeSandbox link even when there was none.
=> Enhance clearError docs + fix bug

package.json, src/components/ApiPage.tsx, src/components/CodeArea.tsx, src/components/codeExamples/clearError.ts, src/components/codeExamples/clearErrorTs.ts, src/components/codeExamples/setValue.ts, src/components/codeExamples/setValueTs.tsx, src/components/codeExamples/setValueTypes.ts
A couple smaller things in this PR.
- remove dead space from format script
- visually de-clutter clearError docs
- add TS, JS and Types + CodeSandbox for setValue
=> Enhance setValue Docs

src/components/ApiPage.tsx, src/components/CodeArea.tsx, src/components/codeExamples/getValues.ts, src/components/codeExamples/getValuesTs.tsx, src/components/codeExamples/getValuesTypes.ts
Getting close to having full TS and Code-sandbox coverage for useForm!
- TS, JS and Types
- Corresponding CodeSandbox's
=> Enhance getValue Docs

src/components/FormFields.module.css
When more than two labels are present margin is broken.
=> Fix label margin

src/components/ApiPage.tsx, src/components/codeExamples/triggerTs.ts
There will be a fix for [Controller](https://github.com/react-hook-form/documentation/issues/324#issuecomment-652691227) coming up next. This is leftovers from last night.
- add V6 JS and TS examples and CodeSandboxes
=> Enhance trigger docs

src/data/en/migrateV5ToV6.tsx, src/data/es/migrateV5ToV6.tsx, src/data/jp/migrateV5ToV6.tsx, src/data/kr/migrateV5ToV6.tsx, src/data/pt/migrateV5ToV6.tsx, src/data/ru/migrateV5ToV6.tsx, src/data/zh/migrateV5ToV6.tsx
=> docs(Migration): fix controller section (#340)

src/components/codeExamples/useFieldArray.ts
Add comment to make demo code more clear.
=> chore: add register usage comment

src/components/UseWatch.tsx, src/components/codeExamples/useWatchTs.ts, src/components/codeExamples/useWatchTypes.ts
Added TS, and JS CodeSandbox and a TS example. Slow but steady 😄!
=> Add useWatch Examples

src/components/V5/codeExamples/form.ts, src/components/codeExamples/form.ts
feat(smart-form): use React.Children.map()
- works with a single child + an array of children
- docs: https://reactjs.org/docs/react-api.html#reactchildrenmap
=> feat(smart-form): use React.Children.map()

src/data/en/api.tsx
=> Fixed typo in docs

src/components/ApiPage.tsx
https://github.com/react-hook-form/react-hook-form/blob/d93e4427cf6c60ea76ac1e3a30e24e8e3ef2f399/src/types/form.ts#L101
=> Change `criteriaMode` defalutValue from `firstErrorDetected` to `firstError`

src/data/en/api.tsx
"If you working on" -> "If you're working on"
=> Fix grammatical error

src/components/AdvancedPage.tsx, src/data/en/advanced.tsx, src/data/es/advanced.tsx, src/data/jp/advanced.tsx, src/data/kr/advanced.tsx, src/data/pt/advanced.tsx, src/data/ru/advanced.tsx, src/data/zh/advanced.tsx
This PR fixes Issue #381. 
- Some minor chinese translation (tribute to GF 😉)
- Fix the title... don't love that the title is used as the key for goToSection... may change this in the future.
=> Fix Side Menu navigation to resolver tab

src/data/home.tsx
Improve translation on terms based on chinese community usage:
- demo  -> 示例
- re-render -> 重渲染
- validation -> 校验
Upgrade cn legacy parts.
=> chore: improve home translation

src/data/home.tsx, src/data/zh/advanced.tsx
Terms translation:
- advanced -> 进阶
- form field -> 表单项  based on antd usage.
Better chinese expression.
Update legacy parts to sync with en version.
=> chore: enhance advanced cn

src/data/zh/faq.tsx
- Better chinese translation for faq page.
- Synchronizing with English version
=> chore: faq-cn-version

src/data/en/faq.tsx
related to : https://github.com/react-hook-form/react-hook-form/pull/2551/files
=> include ie11 info

src/data/en/api.tsx
Added documentation Note for typescript user for controller unable to inject 'onChange, onBlur, value' type props.
=> Update documentation: missing typescript

src/components/codeExamples/accessibleCodeBase.ts, src/components/codeExamples/accessibleCodeFinal.ts
Just a small correction if people are going to be copying this code.
Update: from a quick search, I believe these are the only two.
=> Use `htmlFor` React element attribute in code example

src/data/en/api.tsx
As per additional comments on https://github.com/react-hook-form/react-hook-form/pull/2461
=> [docs] additional details about `defaultValues`

src/data/en/api.tsx
=> Properly space words

src/components/FaqPage.tsx
Related to https://github.com/react-hook-form/resolvers/pull/60
=> docs: add ie11 resolvers info

src/data/en/advanced.tsx
=> Fixed typo in advanced section

src/components/migrateV5ToV6Page.tsx, src/data/V5/kr/api.tsx, src/data/kr/migrateV5ToV6.tsx, src/pages/migrate-v5-to-v6.kr.tsx
---
- Since `migrateV5ToV6Page.tsx` can only show the english page at the moment, I made an optional prop as `content` to inject any translated content by pages.
=> Update Korean translation about V5 documentation

src/components/codeExamples/getStarted.ts
- Current code example is not working.
- I want to update code examples to work as expected not to confuse others reading this documentation.
=> Update getStarted controlledComponent codeExamples

src/components/codeExamples/useFieldArray.ts
- Need to Add a curly bracket to the end of example
=> Update useFieldArray codeExample

src/components/codeExamples/accessibleCode.ts
Hi :)
Just wanted to add the label to make the input accessible. Think you forgot as the other a11y examples already have a label.
(Let me know if Master is not the correct target branch)
=> add label to accessible example

src/data/jp/ts.tsx, src/pages/about-us.tsx
I think the Japanese *TS Support* page was grammatically strange, so I updated src/data/jp/ts.tsx file.　
Thanks  :blush:
=> ts.tsx more accurate JP translation.

src/data/en/api.tsx
=> clarify the meaning of mode="onTouched"

src/data/en/api.tsx
hopefully I worded it correctly
=> add a note to getValues

src/pages/about-us.tsx
I've changed twitter username to be more consistent, so little PR to update it :)
=> Update twitter username

src/components/V5/codeExamples/validationResolver.ts, src/components/V5/codeExamples/validationResolverTs.tsx, src/components/codeExamples/joiResolver.tsx, src/components/codeExamples/joiResolverTs.ts, src/components/codeExamples/validationResolver.ts, src/components/codeExamples/validationResolverTs.tsx
Related to https://github.com/react-hook-form/resolvers/issues/79
I'm not the owner of codesanbox examples,  if someone could update it too :)
=> Examples: use new Joi version

src/data/en/api.tsx, src/data/es/api.tsx, src/data/jp/api.tsx, src/data/kr/api.tsx, src/data/pt/api.tsx, src/data/ru/api.tsx, src/data/zh/api.tsx
Tweaked component name in all languages of V6 docs.
=> Changed FormContext to FormProvider in API docs

src/components/Bday.tsx, src/components/FaqPage.tsx, src/data/en/api.tsx, src/data/en/getStarted.tsx, src/data/es/getStarted.tsx, src/data/jp/getStarted.tsx, src/data/pt/getStarted.tsx, src/data/ru/getStarted.tsx, src/data/zh/getStarted.tsx
Hi, thanks for react-hook-form, very cool library!
Quick PR to fix the casing of TypeScript.
=> Fix casing of TypeScript

src/components/codeExamples/joiResolver.tsx, src/components/codeExamples/joiResolverTs.ts, src/components/codeExamples/superStructResolver.tsx, src/components/codeExamples/zodResolver.ts, src/components/codeExamples/zodResolverTs.ts
Make the resolver examples more uniform, and removes some unnecessary code which may add confusion.
=> Improve resolver examples

src/components/codeExamples/setup.native.ts, src/data/en/advanced.tsx
English documentation update on English test setup
=> fix: solved file problem not found to configure jest in react native in en

src/components/codeExamples/formStateUseEffect.ts, src/components/codeExamples/formStateUseEffectTs.ts, src/data/en/api.tsx
- Update useForm documentation to add clarity
- Add example for useForm in useEffect hook
=> Update docs for formState in useEffect + examples

src/data/resources.tsx
A step-by-step guide on how to handle form in React with React Hook Form
=> How to add React Hook Form in NextJS in resources file

gatsby-browser.js, package.json
Not really sure whats causing the 404, so hoping to force a re-deploy of our documentation with some package upgraded.
=> Bump Gatsby in hopes that it will fix the api issues

src/data/resources.tsx
I created a blog post about using react-hook-form on React Native with TypeScript. And I think it'd be great if it'd be listed in the resources section.
Thank you for the good work!
=> Added new resource article

src/components/FaqPage.tsx
Adds .flat to the list of required polyfills
=> add-flat-to-required-polyfills

src/data/en/api.tsx
=> useFieldArray default value example fix

src/components/GetStartedPage.tsx
npm install yup => npm install @hookform/resolvers yup
=> fixing wrong copy link in getStarted page

src/components/Bday.module.css, src/components/Bday.tsx, src/components/Header.tsx, src/components/HomePage.tsx
Our baby is turning 2 years old. 🥺
=> 2 years old 👦

src/data/en/api.tsx
* The boolean operator should be fixed to be a valid `disabled` attribute
* **not** `isDirty` or **not** `isValid`
=> Fix example code

src/data/resources.tsx
=> Added my article information resource

src/components/codeExamples/defaultExample.ts
the defaultExample‘s code  haven't changed in v7
=> Fix defaultExample code

.gitignore
update the gitignore file to include files generated from yarn 2
=> add yarn 2 files to gitignore

src/components/UseControllerMethods.tsx
removed the repeated row for property `touchedFields`
=> typo in  UseControllerMethods.tsx

src/components/codeExamples/getStarted.ts
@bluebill1049 can you update the codesandbox too ?
https://codesandbox.io/s/react-hook-form-with-ui-library-ts-forked-qjgkx
Related to https://github.com/react-hook-form/react-hook-form/issues/4719
=> docs: update react-select TS example

src/components/codeExamples/getStarted.ts
pass `onBlur`
https://github.com/react-hook-form/react-hook-form/issues/4395#issuecomment-794521966
=> Fix forward.ref example

src/data/en/getStarted.tsx
I can't find description about error.<field name>.type in the given docs, so i have added a brief explanation. kindly ignore if this is mentioned elsewhere.
=> error.<field name>.type description is given

src/components/codeExamples/focusController.tsx
* Add dependencies parameter to `useEffect`
=> Fix Update focusController.tsx

src/components/layout.css
"Courier New" looks weird on Windows, Consolas is definitely more natural
=> Small code font improvement for Windows users

src/data/en/api.tsx
Related to https://github.com/react-hook-form/react-hook-form/issues/5499#issuecomment-855233268
=> Add note about defaultValue/defaultValues

src/data/en/api.tsx
The documentation was pointing to the incorrect props.
This pull request corrects it.
=> Correcting the property referrence

src/components/codeExamples/reactNativeController.ts
- Removed duplicate props.
- The argument of onChange was duplicated with value, so it was fixed.
=> Fix ReactNative part of getStarted page.

.github/workflows/lighthouse.yml, src/components/DevTools.tsx
Changed install dependency version, because current will install the beta version and it still has some issues.
https://github.com/react-hook-form/devtools/issues/79
Signed-off-by: Jie Peng <im@jiepeng.me>
=> docs(devtool): stable devtool

src/components/ApiWatch.tsx
https://react-hook-form.com/api/useform/watch
Problem on screenshot
=> docs: remove surplus round bracket

src/pages/migrate-v6-to-v7.en.tsx
I wasn't sure on the ordering so I just put it on the bottom.
Open to any suggestions on verbiage
=> update migration guide (en) to include shouldUnregister

src/data/kr/advanced.tsx
- Update deprecate Korean translation about `TestingForm` 
- Fix some awkward grammar too
Is there anything problem, Just let me know. 🙏
=> Update Korean translation

src/data/en/api.tsx
Fix type in documentation `Eorrr` -> `Error`
=> Update api.jsx [Fix typo]

src/components/UseFieldArrayContent.tsx, src/data/en/faq.tsx
Fix spacing around `<code>` blocks, and apply some minor grammar fixes.
=> Fix spacing around `<code>` blocks

src/data/en/api.tsx
Updates the descriptions for `setValue`'s config options, `shouldValidate` and `shouldDirty`, with more detailed description of behavior.
=> Update `setValue` config options' descriptions.

LICENSE, src/components/ApiGallery.tsx, src/data/home.tsx
- Some minor english updates for clarity
- In the API page, there were a couple spots where quickly denoting the usage scenarios would be helpful
=> Minor update to documentation for clarity

src/data/en/api.tsx
- Improve grammar
- Update comment to be more percise
Close: #696
=> fix: imprecise comment message in register page

src/components/useForm/resetField.tsx
Update unregistered filed name to be more descriptive
=> docs: Update name to be more descriptive

src/components/useForm/HandleSubmit.tsx
The issue for this is [here](https://github.com/react-hook-form/documentation/issues/701#issuecomment-986024719)
=> chore(HandleSubmit): changed wording

src/components/BuilderPage.tsx
=> feat(form builder): added password type to form builder

src/data/en/getStarted.tsx
Added register type for typescript users. The type is asked by community in so many questions in discussions.
=> Added register type - Update getStarted.tsx

src/data/en/api.tsx
related: https://github.com/react-hook-form/react-hook-form/issues/7591
=> update doc on individual prop overwrite with register

src/components/codeExamples/testingForm.ts, src/data/en/advanced.tsx, src/data/kr/advanced.tsx
ref: https://github.com/react-hook-form/react-hook-form/discussions/7125#discussioncomment-2180265
=> 📝 docs: prevent test example from breaking TS

src/data/en/api.tsx
Fixes https://github.com/react-hook-form/documentation/issues/735
=> fix handlesubmit example with catch

src/data/en/api.tsx
a link to the control API was outdated,
=> update api.tsx incorrect link

src/components/useForm/GetFieldState.tsx
Closes: react-hook-form/react-hook-form#7891
=> 📝 docs(useFieldArray): add method introduction version

src/data/en/api.tsx
=> Add link to control

src/data/en/api.tsx
close https://github.com/react-hook-form/react-hook-form/issues/7970
=> update doc on dirty and dirtyfields

src/components/UseForm.tsx, src/data/en/api.tsx
=> small grammer fix - useForm docs

src/components/useForm/GetFieldState.tsx
Currently we use `isTouch` to refer this property but the correct one should be `isTouched`
=> Use correct prop name isTouched instead of isTouch

src/data/en/api.tsx
=> 📝 docs(useFieldArray): change first update method arg to required

src/data/home.tsx
=> Fixed japanese docs

src/data/ts.tsx
There is a small error in the example around the generic
=> Update `UseFormReturn` example

src/components/ControllerContent.tsx
Fixed typos in sentence under the Video subtitle
=> Fix typos under Video subtitle

src/components/codeExamples/getStarted.ts
Its very nice to have a library like this one, hope this help a little bit with the getStarted page.
Added:
1.  Method onSubmit
2. Example for required with message
=> Add: onSubmit method and required with message example

src/data/V5/en/api.tsx, src/data/V5/es/api.tsx, src/data/V5/jp/api.tsx, src/data/V5/kr/api.tsx, src/data/V5/pt/api.tsx, src/data/V5/ru/api.tsx, src/data/V5/zh/api.tsx, src/data/V6/en/api.tsx, src/data/V6/es/api.tsx, src/data/V6/jp/api.tsx, src/data/V6/kr/api.tsx, src/data/V6/pt/api.tsx, src/data/V6/ru/api.tsx, src/data/V6/zh/api.tsx, src/data/en/api.tsx, src/data/en/getStarted.tsx, src/data/es/api.tsx, src/data/es/getStarted.tsx, src/data/jp/api.tsx, src/data/jp/getStarted.tsx, src/data/kr/api.tsx, src/data/kr/getStarted.tsx, src/data/pt/api.tsx, src/data/pt/getStarted.tsx, src/data/ru/api.tsx, src/data/ru/getStarted.tsx, src/data/zh/api.tsx, src/data/zh/getStarted.tsx
- update doc on `useFieldArray` with newly added rules prop
close #801
=> Close #801

src/components/useForm/GetFieldState.tsx
close issue: https://github.com/react-hook-form/react-hook-form/issues/8786#issuecomment-1204570567
=> improve doc on getFieldState

src/data/en/api.tsx
Refine explanation of behaviour of isDirty when keepDefaultValues is true when calling reset function
=> Refine explanation of isDirty when keepDefaultValues set

src/components/tsPage.tsx, src/data/ts.tsx
https://github.com/react-hook-form/react-hook-form/pull/8837
=> v7.35.0 update ts page

src/components/codeExamples/v6/zodResolverTs.ts, src/components/codeExamples/zodResolverTs.ts
Replacing `IFormInput` with `Schema` on `onSubmit` function
=> Fix onSubmit `data` type on useForm zod resolver code example

src/data/ts.tsx
=> feat: add `UseFormReturn` type

.github/workflows/lighthouse.yml, src/components/FaqPage.tsx, src/components/codeExamples/importKeystroke.ts, src/data/en/faq.tsx
I create a new way to build a FAQ page, it's more simple and prevent bug when we remove link questions. 
- Use map to render our questions and add a `<CodeArea ... />` inside a faq json. 
- Use a REMOVE_QUESTIONS_FOR_LIST variable to say how much questions we need to remove on render. 
- Create a new example code file to question **Why is the first keystroke not working?** before this code is inline on project.
This new implementation  fix a issue on FAQ page on production. We have a question that doesn’ t appear on sidebar menu.  Now the sidebar menu and questions is linked if appear on menu appear on question view.
=> Proposal: to new way to make FAQ page

src/components/UseForm.tsx
related: https://github.com/react-hook-form/react-hook-form/issues/9290
=> update shouldUseNativeValidation detail on mode related issue

src/data/en/advanced.tsx, src/data/en/faq.tsx, src/data/en/getStarted.tsx
I have been using RHF professionally at the agency that I work for. It has been great to work with! I noticed a few areas in the documentation that could be worded differently to improve understanding/clarity. 
I did not attempt to change any of the meaning, just recommendations on wording that helps clarify what is being communicated.
=> Documentation copy improvement recommendations

src/components/ControllerContent.tsx
First PR here, hope I have it right. Correcting simple typo.
=> ControllerContent.tsx typo: useController > Controller

src/data/en/api.tsx
=> 📝 docs(UseFieldArray): update fielderror link

src/components/Resources.json
Adding a link to the playlist of the videos I've recently released. 
More videos will follow in the playlist I linked.
I'm not sure about the creation date. Or the timezone. Is that generated somehow?
=> Add video link for youtube playlist

src/data/ts.tsx
- Added `React` import to make the code work
- Separated types imports
- Changed `TFormValues` constraint to `FieldValues` to reuse code
=> Small changes to UseFormReturn code example

src/components/codeExamples/formComponent.ts
=> Fix jsx for Form example

src/data/resources.tsx
This pull requests add a new third party binding for Chakra UI
=> Add new third party binding (react-hook-form-chakra)

src/components/UseFieldArrayContent.tsx
Corrected the name of `Controller` component
=> fix: correct typo in UseFieldArrayContent

src/data/resources.tsx
I made a very simple binding for antd: <https://github.com/jsun969/react-hook-form-antd>
=> Add Ant Design binding

src/components/Footer.tsx, src/components/Nav.tsx, src/data/nav.tsx
Did another round of looking for dead links and found these two that were introduced when I separated resources
=> fix: dead link in mobile nav and footer

src/data/ts.tsx
=> Update controller types

src/components/AdvancedPage.tsx, src/components/logic/getEditLink.tsx, src/components/mdx/mdx.tsx, src/components/tsPage.tsx, src/content/advanced.mdx, src/content/faq.mdx, src/content/ts.mdx, src/pages/advanced-usage.tsx, src/pages/ts.tsx
Same as previous PR.
Nothing particularly tricky yet
=> feat: moving advanced and ts page to mdx

src/content/docs/useform.mdx
removed semicolon in useform page.
=> refactor in useForm page

src/content/docs/useform/watch.mdx
according to issue [#998 ]
added typescript and edited javascript code for watch in field array -> https://react-hook-form.com/docs/useform/watch
also added new codesandbox link for it
=> Adding Typscript code in Watch in Field Array in useForm/watch 

src/components/ApiGallery.module.css
Brought back the hover effect on API tiles, lost due to migration
=> Fixed  Hover state missing (#983)

src/content/docs/useform.mdx
=> defaultValues - link to legacy React docs*(issue#993) - updated link

src/content/get-started.mdx
=> 📝 docs(GetStarted): refactor MUI named export

src/data/api.tsx
=> 📝 docs(register): remove deprecated ref prop

src/components/UseFieldArrayContent.tsx
=> docs: fix typo, replace "this this" with "this"

src/content/docs/useform/seterror.mdx
=> fix: grammatical errors

src/components/Nav.module.css, src/components/Nav.tsx
- [Discord logo change](https://support.discord.com/hc/en-us/articles/1500009438682-A-Fresh-New-Look-to-Celebrate-Our-6th-Birthday)
- [Discord new logo](https://discord.com/branding)
- [Twitter/X new logo](https://about.x.com/pt/who-we-are/brand-toolkit)
Before
After
_Ive just noticed that a vscode extension changed the order of some classes in the file, but I dont think this is a problem._
=> Update social media logos

src/content/ts.mdx
Update website docs (TS section)
=> docs: update ts.mdx

src/content/docs/useform.mdx, src/content/ts.mdx
=> feat: Add useForm disabled prop description

src/components/Menu/Menu.tsx
Reverts react-hook-form/documentation#1085
=> Revert "Added scroll based menu highlight feature"

src/data/resources.tsx
=> docs: add catalin rhf articles

src/pages/404.module.css, src/pages/404.tsx
Addressing https://github.com/react-hook-form/documentation/issues/1125
Before:
After:
=> Fix: 404 page layout

src/content/docs/useformstate/errormessage.mdx
added missing colon that i noticed while scrolling through
=> super simple typo fix for errormessage.mdx
