src/components/ApiRefTable.tsx
Just a quick fix, noticed this whilst looking at the validation docs.
=> Fix slashes in regex validation example

src/components/codeExamples/defaultExample.ts
Great library/site!
I was playing around with the examples and noticed there is a small issue with the code for the default example (first one here: https://react-hook-form.com/get-started). 
The two issues are:
1. The error object is checking the wrong field for errors (checking errors from the `example` field, not the `exampleRequired` field)
2. The error `span`, is being rendered a string instead of html. 
This fixes both of those issues. 
Thanks!
=> fix(example): fix bug in defaultExample

src/components/ApiPage.tsx
It was [accidentally removed](https://github.com/react-hook-form/react-hook-form-website/commit/d94abba830342d0a3fba6f9da3b9625c26a4157a#diff-8e2137ec74d914a55499d50c2858f9bcL837).
=> Fix: add missing formState API documentation

src/components/ApiRefTable.tsx
My understanding is that this was supposed to read, "... create nested _form_ fields".
If it is supposed to read a different way, I'm happy to update the PR.
=> Fix typo in useForm register API docs

src/components/ApiPage.tsx
I was about to add description for `validateSchemaOption` but never understood its uses like I thought setting `abortEarly` to `false` would return all errors instead of one.
=> Add `clearError` to the side menu.

src/components/codeExamples/typeScript.ts
The `errors` object is missing from the destructuring example in the TypeScript section.
=> Minor correction to add errors to useForm initialization

src/components/codeExamples/accessibleCodeFinal.ts, src/components/codeExamples/formWizard.ts
I found some typos translating 'Adavanced' page
* in the accessbility example, `id` doesn't match with `aria-describedby`
* Wizzard -> Wizard
=> fix typos in example codes

src/components/ApiPage.tsx, src/components/BuilderPage.tsx, src/components/HomePage.tsx, src/components/Nav.tsx, src/components/learnMore.tsx, src/components/logic/translateLink.ts
1. Applied `translatedLink` to some navigations which are missing it.
2. When changing the language with the `select` component on the upper right side, it also changes the current pathname following the selected language.
The second one looks a bit dirty and might be unreadable. We can revert it anytime.
=> Improve i18n navigations

src/components/codeExamples/reactHookFormCode.ts
validation function should returns true on success and error string on failure.
here's example of original behaviour and fixed:
=> fix validation example on a main page

src/data/api.tsx
I'm not a native English speaker, but the following looks more correct to me.
=> Fix language in API documentation

src/data/getStarted.tsx
changed from innerRef to inputRef for Material UI TextField.
only japanese was not changed.
related: https://github.com/react-hook-form/react-hook-form-website/pull/109
=> update workWithUI description in getStarted page

src/components/codeExamples/formContextPerformance.ts
I noted an error in one of the examples provided on your Advanced Usage page, when I attempted to utilise same in my project.
I created a CodeSandbox for review if required, although it appeared to be a pretty straightforward fix (although I'm no memo/useMemo expert).
[https://codesandbox.io/s/optimistic-worker-phhks](https://codesandbox.io/s/optimistic-worker-phhks)
Cheers
=> Fix broken example React.memo -> React.useMemo

src/components/ApiPage.tsx
Needed to be absolute.
Note: this may also be an issue [on this line](https://github.com/react-hook-form/react-hook-form-website/blob/d8912d9521462d6fb2f04effb238110ae3c63e7e/src/data/es/api.tsx#L302), but I am unfamiliar with the codebase and unable to reproduce the error on that page.
=> fix: broken link to advanced usage

src/components/codeExamples/connectForm.ts
Corrected `props.children` to `children` in connectForm example.
Thank you! 😸
=> Fix connect form example

src/components/ApiPage.tsx
Hello.
When a user clicks the `advancedUsage` button on a translated page, 
the page doesn't show up correctly.
So I fixed a `link` parameter, from `/advanced-usage` to `advanced-usage`.
=> Fix navigation error when using translated page

src/components/codeExamples/reduxFormCode.ts
This addresses #165. I've also fixed the equality check on the same line - unless I'm misinterpreting the goal of that validation, I believe it should be `values.username === "admin"` rather than `values.username !== "admin"`, similar to the Formik example.
=> Fix Redux Form example in Library Code Comparison

src/components/ApiPage.tsx
The **Advanced Usage** button on https://react-hook-form.com/api takes to https://react-hook-form.com/api/advanced-usage which does not exist.
This PR fixes the broken link.
=> Fix Advanced Usage broken link

src/components/codeExamples/controlledMixedUncontrolled.ts
Spreading default values to avoid material-ui error being printed on console.
> Material-UI: you have provided an out-of-range value `undefined` for the select component.
> Consider providing a value that matches one of the available options or ''.
> The available values are `10`, `20`, `30`.
=> Fixing reset button data

src/components/codeExamples/connectForm.ts
I think it is good to make it explicit where those functions are coming from.
=> fix: add missing components in import line

src/components/ApiPage.tsx, src/components/codeExamples/getStarted.ts, src/data/en/advanced.tsx, src/data/en/api.tsx, src/data/en/getStarted.tsx, src/data/home.tsx
**Disclaimer:** I'm not a native english speaker, nor a user of this library.
I saw some typos and sentences I had trouble to understand on this website. Therefore I spent some time to try to improve it. I think it's better, but probably still very far from perfect since I'm neither a native english speaker nor a very good writer. I just hope that I haven't made more mistakes than there previously was :crossed_fingers: . Also, I did not review the entire website because I lost patience after a while.
Lastly, I wonder why the website is that slow. In particular, the [API](https://react-hook-form.com/api#register) page makes my CPU crazy. Changing the `Register options` radio buttons makes my Firefox lag for one whole second for no apparent reason. It looks slightly better on Chrome, but …
=> Multiple typo fixes and rephrases.

src/components/codeExamples/connectForm.ts
In Advanced Connect Form example, `useStateMachine` hook is not used and unnecessary.  
URL: https://react-hook-form.com/advanced-usage#ConnectForm
=> Remove state machine hook import in connect form example

src/components/Form.tsx
On my little quest to understand how the regression happened, I assumed there was an API change. Looking through the releases found [v4.1.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v4.1.0) and the corresponding change react-hook-form/react-hook-form#711.
This change respects new API by making `touched` an array again how the rest of the rendering code expects.
=> fix #184 expect formState.touched to be an object

src/components/codeExamples/reduxFormCode.ts
I was looking at the examples on the home page today and the end of the redux form example didn't look quite right. I'm pretty sure this is what it should be.
=> fix: redux form example

src/data/kr/api.tsx
This PR resolves [this comment](https://github.com/react-hook-form/react-hook-form-website/commit/8b7cba83e8673dd37d2b162c07f82d91596b7793).
- `useFieldArray` translation was already outdated.
- Performance comparison video link
- Mentioning `watch` API
- `Controller`
- About `defaultValues`
=> Update korean translation (useFieldArray, Controller)

src/components/codeExamples/controller.ts
Here (https://react-hook-form.com/api#Controller) we have an example for Controller with onChange callback.
As far as I see from release notes for V5.0.0 (https://github.com/react-hook-form/react-hook-form/releases/tag/v5.0.0) we need to return value instead of an object like `{ value: selected }`
I use react-hook-form with `https://ant.design/` and I've found it useful to update this example
=> Controller:onChange callback have to return value instead of object

src/components/codeExamples/customHookWithValidationResolver.tsx
Noticed a small typo in the [docs](https://react-hook-form.com/advanced-usage#CustomHookwithValidationResolver).  
Changed `useFromm` to `useForm`
=> fix: typo from useFromm to useForm

src/data/kr/advanced.tsx, src/data/kr/api.tsx, src/data/kr/faq.tsx
* New note for `validationResolver` about handling error
* New FAQ entries about the ternary operator and working `Controller` with the `submitFocusError` option.
* New API - `Controller#onFocus`
* New advanced usages
- Custom hook with the validation resolver
- Working with the visualized list
=> Update Korean translation 200401

src/components/codeExamples/useFieldArray.ts, src/components/codeExamples/useFieldArrayArgument.ts
If provide `register` without calling, examples works incorectly.
https://codesandbox.io/s/nervous-raman-7en3o
=> FIX: register call in useFieldArray examples

src/data/kr/api.tsx
Noticed a small typo in the [docs](https://react-hook-form.com/kr/api#Controller).
Changed `registter` to `register`
=> fix:typo from registter to register

src/components/codeExamples/useFieldArray.ts
The current docs as misleading when they should `append({ name: "test" })` as if the initial value of the input would be `"test"`, while if no `defaultValue` is added to the input, the newly appended input will be empty by default.
=> Added `defaultValue` to useFieldArray example

src/components/codeExamples/reactNative.ts
Add JSON.stringify to prevent React Native error `Value for message cannot be case from ReadableNativeMap to String` when running `onSubmit` function
=> Add JSON.stringify()

src/components/codeExamples/enzymeInput.tsx, src/data/en/faq.tsx
Fixes https://github.com/react-hook-form/react-hook-form/issues/1382.
I'm not picky about the phrasing of this, and would be happy to change it if requested or just let a maintainer edit. 🤗
=> Added explanation for Enzyme testing to FAQs

src/components/ApiPage.tsx, src/data/es/api-v5.tsx, src/data/es/api.tsx
Currently, the button ("Learn Advanced Usage") at the end of API page https://react-hook-form.com/api/ is getting 404. This changes will fix the link.
=> Fix advanced link on API page

src/components/BuilderPage.module.css
When Form Builder is opened we can click button "scroll to top". After clicked "scroll to top" "close button" from a Form Builder overlap a language selector. In this PR has been changed z-index Form Builder "modal" which is higher than "scroll to top" button.
=> Hide scroll to top button when Form Builder is open

src/components/codeExamples/clearError.ts
Remove duplicated import of clearError method
=> Fix typo in clearError code example

src/data/en/api-v5.tsx, src/data/en/api.tsx, src/data/es/api-v5.tsx, src/data/es/api.tsx, src/data/jp/api-v5.tsx, src/data/jp/api.tsx, src/data/kr/api-v5.tsx, src/data/kr/api.tsx, src/data/pt/api-v5.tsx, src/data/pt/api.tsx, src/data/ru/api-v5.tsx, src/data/ru/api.tsx, src/data/zh/api-v5.tsx, src/data/zh/api.tsx
* Fix go to section validationSchema
P.S.
I have noticed @bluebill1049 you have upgraded packages (also Prettier) so https://prettier.io/docs/en/options.html#arrow-function-parentheses
> First available in v1.9.0, default value changed from avoid to always in v2.0.0
and thats why Prettier in precommit reformatted these files
=> fix validation schema go to section

src/data/en/advanced.tsx
This PR is to fix the typo on the Advanced Usage page.
I fixed typo that was no space.
=> Fixed typo on Advanced Usage page

src/components/codeExamples/formContextPerformance.ts
I fixed example code on FormContext Performance of Advanced Usage.
I think `useMemo()` should be used to memorize expensive  value but not a component. 
Therefore I fixed to use `memo()`.
codesandbox: https://codesandbox.io/s/react-hook-form-useform-template-gtx2c?file=/src/index.js
=> Fixed example code on FormContext Performance

src/components/ApiPage.tsx
I fixed link to navigate to Advanced Usage Page.
The next page is not displayed if I clicked the "Learn Advanced Usage" button when translated to a language other than English.
=> Fixed APIPage link to navigate to Advanced Usage Page

src/components/ApiRefTable.tsx
It was rendering a semicolon inside an object.
Fixed version 👇 
```
register({
validate: value => value === '1'
})
```
=> Fixed example in documentation

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, src/components/Footer.tsx, src/components/Nav.tsx
Modified footer to add link to docs github:
Changed the github header Link to take you to the [react-hook-form general github](https://github.com/react-hook-form) repo. This change makes it easier to see everything react-hook-form has to offer.
Added CODE_OF_CONDUCT.md and CONTRIBUTING.md with small changes from main [react-hook-form page](https://github.com/react-hook-form/react-hook-form). 
ZEIT changed its name to [Vercel](https://vercel.com/). #what-21-million-in-funding-does
**This PR Merges into master, not V6 like my other PR's**
=> Improve Contributor Experience 

src/components/ApiPage.tsx, src/components/GetStarted.tsx, src/components/GetStartedPage.tsx, src/components/V5/ApiPageV5.tsx, src/components/V5/codeExamples/resetControllerTs.ts, src/components/codeExamples/getStarted.ts, src/components/codeExamples/resetControllerTs.ts
This PR focuses on creating a TS equivalent to one of Bill's more important [CodeSandbox examples](https://codesandbox.io/s/react-hook-form-controller-079xx). 
Also added some Basic TS Code examples for the API and GetStarted.
=> Update Important Code Sandbox + Add TS examples

src/components/ApiPage.tsx
https://react-hook-form.com/api#handleSubmit has:
`handleSubmit: (data: Object, e: Event) => () => void`
But the Typescript types in https://github.com/react-hook-form/react-hook-form/blob/master/src/types/form.ts are:
```
export type SubmitHandler<TFieldValues extends FieldValues> = (
data: UnpackNestedValue<TFieldValues>,
event?: React.BaseSyntheticEvent,
) => void | Promise<void>;
...
handleSubmit: <TSubmitFieldValues extends FieldValues = TFieldValues>(
callback: SubmitHandler<TSubmitFieldValues>,
) => (e?: React.BaseSyntheticEvent) => Promise<void>;
```
To simplify for the documentation, that line should be something like:
`handleSubmit: ((data: Object, e?: Event) => void) => (e?: Event) => void`
At its core handleSubmit executes a [partial …
=> Fix type signature for handleSubmit in docs

src/components/codeExamples/formikCode.ts, src/components/codeExamples/reactHookFormCode.ts, src/components/codeExamples/reduxFormCode.ts
Currently, the examples that have email regex force the TLD (top-level domains) to be in the length range of 2-4 characters. This tripped me up for a little while when testing the sample code as we use "*@xyz.digital" for our emails and caused confusion as to if there was a bug with react-hook-form or the regex.
Hope it saves someone else some time in the future.
=> fix examples with email regex to support all TLD's

src/components/CodeArea.tsx
I fixed bugs that code examples are not displayed if you access to `register` description section in the API page and you clicked radio button.
=> Fix CodeArea component bugs

src/data/en/advanced.tsx, src/data/jp/advanced.tsx
This is proposal.
I changed from `mutationobserver-shim` to `jest-dom`. The reason is please check this tweet https://twitter.com/TestingLib/status/1277219837849137153
If this change is make sense, please merge. I'm glad if you translate.
=> Fixed mutationobserver-shim to jest-dom

src/data/en/migrateV5ToV6.tsx
I'm assuming you meant to say `setValue` and not `setError`.
=> fix: Fix usage of setValue in V6 migration guide.

src/components/codeExamples/accessibleCode.ts, src/components/codeExamples/accessibleCodeFinal.ts
I fixed code example in accessibility section.
Because `aria-description` is not read dynamically. And if you use `role="alert"` at initial rendering, screen reader unintended to read contents.
About `role="alert"`
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute
=> Fixed code example in accessibility section of advanced page

src/components/Controller.tsx, src/components/V5/ApiPageV5.tsx, src/components/V5/ControllerV5.tsx, src/data/V5/en/api.tsx, src/data/V5/es/api.tsx, src/data/V5/jp/api.tsx, src/data/V5/kr/api.tsx, src/data/V5/pt/api.tsx, src/data/V5/ru/api.tsx, src/data/V5/zh/api.tsx, src/data/en/api.tsx, src/data/es/api.tsx, src/data/jp/api.tsx, src/data/kr/api.tsx, src/data/pt/api.tsx, src/data/ru/api.tsx, src/data/zh/api.tsx
This PR fixes #324. (or at least address some of what was discussed there)
- Separate Code for V5 vs. V6 controller (I don't love how this is done [pure code duplication rn]), Am postulating a better structure)
- A bunch of tweaked CodeSanbox's
=> Separate CodeExamples for V5 vs. V6

src/data/en/migrateV5ToV6.tsx, src/data/es/migrateV5ToV6.tsx, src/data/jp/migrateV5ToV6.tsx, src/data/kr/migrateV5ToV6.tsx, src/data/pt/migrateV5ToV6.tsx, src/data/ru/migrateV5ToV6.tsx, src/data/zh/migrateV5ToV6.tsx
Attribute `name` was concatenated with `<Controller`, this PR fixes the typo.
=> docs(Migration): fix controller section typo (#340)

Global.d.ts
fix css module type declaration error based on https://stackoverflow.com/questions/41336858/how-to-import-css-modules-with-typescript-react-and-webpack/51536973#51536973
=> fix: css declaration

src/components/ApiRefTable.module.css, src/components/ApiRefTable.tsx
I fixed css and performance with Register Options feature in API page.
- I added `cursor: pointer;`
- I replaced from `Prism.highlightAll` to `Prism.highlightAllUnder` because it is too late when I clicked Register Options.
=> Improve performance in api page

src/data/zh/getStarted.tsx
Enhance and sync get-start part chinese version. Major change points includes: 
- chinese terms
- *Uncontrolled component*  `不受控制的组件` to `非受控组件` based on react chinese doc and chinese community usage.
-  *validation* `验证` to `校验` based on ant-design usage.
- *external ui libraries* `外部ui组件库` to `第三方ui组件库` based on chinese community usage.
- Sync current en docs, and correct some links with `translateLink`.
- change something to make it easier to understand in chinese.
=> chore: enhance get-start chinese

src/components/CodeArea.tsx, src/components/layout.tsx
Related to #350, I fixed render-blocking in `Layout` components. To fix this, I move `Prism.highlightAll` to `CodeArea` component and I replaced to `Prism.highlightAllUnder`. This problem occur when it toggle light mode and dark mode or it navigate another page.
=> improved render-blocking

src/components/Nav.tsx
sync select state with location.
Steps to reproduce bug.
- click  https://react-hook-form.com/api
- click useForm v5 and select chinese
- click v6 then navigate to english api page but select value not update because of defaultValue props.
=> fix: language select state

src/components/codeExamples/customHookWithValidationResolver.tsx
Hi,
`useMemo` from `react` package is used in customHookWithValidationResolver code example but its related import is missing from the codes, so I just added it to the import statement.
=> add useMemo import to customHookWithValidationResolver code example

Global.d.ts, README.md, gatsby-node.js, gatsby-ssr.js, package.json, yarn.lock
- Cleanup some dead filed
- Updated package dependencies to the latest and greatest (this was done to avoid as many bugs as possible going forwards)
- Bump react-hook-form version 6.0.2 yay!
- Bump node version 12 -> 14 (12 will eventually be unsupported)(I can change it back if anyone wants, just a pet peeve of mine #nvm)
- Delete Global.d.ts (it wasn't doing what it was supposed to)
P.S. I'm hoping this weekend I'll have the time to work on a larger refactor of the api page code. This was some cleanup in preparation. More info to come.
=> Cleanup before a heavy lift

src/components/ApiPage.tsx
Clicking the link when the current location is something like `/api/#formState` would result in a 404 page `/api/advanced-usage`
=> Fix advanced-usage path on ApiPage

.github/workflows/lighthouse.yml, .lighthouserc.js, package.json
This is the most basic setup for [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci). It runs a lighthouse check, creates a temporary report (saved for 7 days), and ensures the first-contentful-paint is not any slower then 2.5s.
To add in the future:
- More assertions (They have a list of [recommended assertions](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#add-assertions) but I want to get the base setup working before adding more.
- [nice configuration](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#github-status-checks) with github 
- Create [our own server](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#the-lighthouse-ci-server) to check lighthouse stats. This would be …
=> Basic lighthouse setup

src/components/ApiPage.tsx
This PR fixes Issue #375.
- The real issue is that the refs were declared in an improper order... ([Lines 166 and 167](https://github.com/react-hook-form/documentation/compare/master...pmaier983:fix/navigation-highlighting?expand=1#diff-8e2137ec74d914a55499d50c2858f9bcL166)) but to find this I first refactored the entire highlighting useEffect to be more functionally coded. What I'm saying is, this PR could be a 2-liner if the refactoring is not up to snuff.
=> Simplify useEffect and fix navigation highlighting

src/components/V5/codeExamples/getStarted.ts, src/components/codeExamples/getStarted.ts, src/components/codeExamples/smartForm.ts, src/components/tsPage.tsx
This is part of the https://github.com/react-hook-form/documentation/pull/378 PR to remove charged terminology
=> Add "other" to gender options and sort alphabetically

src/components/codeExamples/useFieldArray.ts
In the Field Arrays example the _firstname_ is a property of the object _test_, but is being shown as a string _"test.firstname"_. With this pull request both _firstname_ and _lastname_ are being shown properly.
=> fix: default value now is an object property and not a string

src/components/codeExamples/useFieldArray.ts
This sets the `name` of the inputs the same way as the linked codesandbox 
example (https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv) does.
=> Update code to match linked codesandbox

src/components/GetStartedPage.tsx
bug fix.
getStarted page menu cannot navigate to right place except english titles currently because of keys  in `sectionRef` uses other language chars while `goToSection` uses an enlingsh one.
=> fix: use getstartedEn title

src/data/es/api.tsx, src/data/jp/api.tsx, src/data/kr/api.tsx, src/data/pt/api.tsx, src/data/ru/api.tsx, src/data/zh/api.tsx
Fixed a syntax error in html attribute.
=> fix typo `render()` -> render={}

src/data/en/api.tsx
Fixes a typo on the code example. `props` isn't available as everything is destructured.
=> Fix code example in Controller docs

src/data/en/api.tsx
The note for `errors { types }` contains the old setting name of `validateCriteriaMode` instead of the new `criteriaMode`.
=> Update `validateCriteriaMode` to `criteriaMode`

src/data/en/api.tsx
It seems the documentation seems to imply Validation will only trigger until an input has been touched "Validation will trigger until input is touched". This should be "won't" trigger until and input is touched.
=> Updated onTouched method

src/components/codeExamples/strictlyTyped.ts
According to discussion in this issue [Checkbox when using `useTypedController` not working as expected](https://github.com/react-hook-form/react-hook-form/issues/2678#issue-683874150) on the `react-hook-form` repository. This PR updates the code example on how to use Strictly Typed with implementation of checkbox to be more inline with example on how to use Controlled checkbox.
=> Update Strictly Typed code example with correct implementation of using checkbox with TypeController

src/data/en/ts.tsx
The section for `UseFormMethods`,  there is no space  between `of` and `useFormContext`. So, I insert `&nbsp;` explicitly.  https://react-hook-form.com/ts/
=> Insert &nbsp; at UseFormMethods section for visibility.

src/components/AdvancedPage.tsx, src/components/ApiPage.tsx, src/components/FaqPage.tsx, src/components/GetStartedPage.tsx, src/components/V5/ApiPageV5.tsx, src/components/tsPage.tsx
This PR adds id's to as many anchored links as I could find. This will allow docSearch to better map to them, because currently it pastes `#gatsbyfocuswrapper` instead of anything useful.
=> Add id to all "goToSection" tags

src/components/codeExamples/formWizard.ts, src/data/en/advanced.tsx, src/data/es/advanced.tsx, src/data/jp/advanced.tsx, src/data/kr/advanced.tsx, src/data/pt/advanced.tsx, src/data/ru/advanced.tsx, src/data/zh/advanced.tsx
In [Wizard (funnel / multi-step) form](https://codesandbox.io/s/react-hook-form-wizard-form-13yud?file=/src/Step2.js) example:
`Step 2` component should be `Step 2`, not `Step 1`.
It may make example reader confused.
=> Rename wizard step2 component

src/data/en/api.tsx
Not sure on this one, but I'm guessing at some point somebody translated this from markdown, and missed these backticks when they did so.
=> Nit: Fix stray markdown backticks?

src/components/V5/codeExamples/setValueTs.tsx, src/components/codeExamples/setValueTypes.ts
As identified in a Discord thread, examples of `setValue([{..., ...}])` are no longer valid.
=> [docs]: remove invalid examples of setValue()

src/components/layout.tsx
If scrolled to the top of a page the edit and scroll buttons are hidden, but if you hover over the hidden element it still changes the cursor and clicking also works. This PR hides the buttons properly.
=> Hide edit button properly

src/components/Nav.module.css
Some small fixes for centering and padding for the language select.
- Vertical align selected language.
- Fix caret icon and longer language names overlap.
Current styling:
Fixed styling:
=> Fix centering and padding lang select

src/data/en/faq.tsx
I thought i should remove the repeated `is` and changed the wording a bit. Please lemme know if it was unneeded.
=> Fixed wording typo in faq

src/components/FaqPage.tsx, src/components/ValidationResolver.tsx, src/components/codeExamples/joiResolver.tsx, src/components/codeExamples/joiResolverTs.ts, src/components/codeExamples/superStructResolver.tsx, src/components/codeExamples/validationSchema.ts, src/components/codeExamples/validationSchemaTs.ts, src/components/codeExamples/zodResolver.ts, src/components/codeExamples/zodResolverTs.ts, src/data/en/api.tsx, src/data/en/faq.tsx, src/data/en/getStarted.tsx
👋🏻 
Maybe this PR should be merged when resolvers V1 is officially released
I'm not the owner of resolvers examples on codesandbox in order to udpate import, the list of codesandbox to update:
https://codesandbox.io/s/react-hook-form-validationschema-v6-2l77g
https://codesandbox.io/s/react-hook-form-validationschema-v6-ts-fpebh
https://codesandbox.io/s/react-hook-form-joiresolver-v6-yejqe
https://codesandbox.io/s/react-hook-form-joiresolver-v6-ts-jwg5g
https://codesandbox.io/s/react-hook-form-v6-superstructresolver-ed67i
=> Update resolvers examples + add Zod examples

src/components/codeExamples/getStarted.ts
`String` needs to be `string` for the _Register fields_ example to compile
=> fix typescript type in Register fields example

src/data/en/api.tsx
- Make it clearer that defaultValues is required for every field in the array.
- Provide examples for using field.id as the component key.
- Spelling fixes
I edited this directly on GH so please excuse any formatting issues.
Related to https://github.com/react-hook-form/react-hook-form/issues/3335
=> Language tweaks for useFieldArray

src/components/codeExamples/accessibleCodeBase.ts, src/components/codeExamples/accessibleCodeFinal.ts
Hi !
When working on form validation with [Advanced - Accessibility (A11y)](https://react-hook-form.com/advanced-usage), I realised the forms for accessibility do not work as it misses a name attribut to the input tag. 
See error in console below:
With my fix, the validation on form works properly:
=> Advanced - Accessibility (A11y): add name attribute to fix the forms

src/data/en/api.tsx
To find this goto, https://react-hook-form.com/api#useFieldArray and the example is just below the text: `Important: Because each input can be uncontrolled, id is required with mapped components to help React to identify which items have changed, are added, or are removed.`
=> Fix invalid example defaultValue to name

src/components/FaqPage.tsx
Polyfills for `String.startsWith`, `Array.find` and `Array.includes` are also required for IE11, but not mentioned in the docs right now.
=> Add other necessary IE11 polyfills to the Faq Page

gatsby-browser.js, src/state/setting.ts
This *should* solve issue #468. 
I had difficulty testing the fix though as currently localhost only saves to localStorage (even if:
```
createStore(
{
formData,
language,
setting,
},
{
storageType: window.sessionStorage,
}
)
```
Also I'm not 100% sure this is correct as you mention *user settings* and I interpreted that as `localStorage`, but I could be wrong.
=> little state machine local storage > session

src/data/en/api.tsx
Adds a concise code example / do/don't explaining about how to use the `formState` proxy, inspired by [this](https://github.com/react-hook-form/react-hook-form/issues/3673) issue
=> add further explanation code about formState props

src/components/ApiRefTable.tsx
I was using setValueAs alongside valueAsNumber in my code, and expected the setValueAs function to simply receive a number instead of a string. Instead, the function was ignored.
Looking at https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/getFieldValue.ts#L49, I see this experience is by design:
```ts
return valueAsNumber
? +value
: valueAsDate
? (ref as HTMLInputElement).valueAsDate
: setValueAs
? setValueAs(value)
: value;
```
So I thought it would be helpful to clarify this in the documentation.
=> Clarify that valueAsNumber and valueAsDate supersede setValueAs

src/components/tsPage.tsx
Hi, thanks for your great library!
I noticed, that the ts page shows the wrong title (and description) for the [UseControllerMethods](https://react-hook-form.com/ts#UseControllerMethods) and [UseControllerOptions](https://react-hook-form.com/ts#UseControllerOptions) sections. Both use the same data as the `UseFieldArrayOptions` section. Probably due to copy and paste.
This PR fixes this.
=> Fix titles on ts page

gatsby-browser.js, src/data/en/advanced.tsx, src/data/es/advanced.tsx, src/data/jp/advanced.tsx, src/data/kr/advanced.tsx, src/data/pt/advanced.tsx, src/data/ru/advanced.tsx, src/data/zh/advanced.tsx
The bug was brought up here: https://spectrum.chat/react-hook-form/help/official-docs-example-is-not-working-please-check~aa1204e1-d833-4089-b381-c7952d8163d6. I fixed the codesandbox and moved it to our codesandbox "area".
=> Fix form wizard code sandbox

src/components/codeExamples/useController.ts
Typo: https://react-hook-form.com/api/#useController
=> useController example fix list of imports

src/data/resources.tsx
I've created an article about react-native-hook usage in React Native.
This implementation uses new `useController` hook which makes codebase much better to understand for developers. This is a new approach as most older tutorials describe the usage of `<Controller />` component.
=> Add "Handy form validation in React Native" article to resources

src/components/DevTools.tsx
I ran into an issue using the wrong version with the v7 with v2 of devtools with `typeError: getValues is not a function` via npm tag https://www.npmjs.com/package/@hookform/devtools
updated display and copy text
=> Update to v7 tag documentation for compatibility with devtools

src/components/codeExamples/schemaValidation.ts
The code example for the Javascript Schema Validation, had the deprecated way to get the errors from useForm. I just updated it to the V7 way. (Typescript version is ok)
=> Patch: Add new error handling on schema validation

src/components/codeExamples/defaultExample.ts, src/components/codeExamples/defaultExampleTs.tsx, src/components/codeExamples/v6/defaultExample.ts, src/components/codeExamples/v6/defaultExampleTs.tsx
Hello guys,
Just a little PR to be able to copy/paste the example of `Get started` (here https://react-hook-form.com/get-started/) without have to make some changes (remove of brackets).
=> Remove brackets in default examples to be able to copy/paste it

src/data/en/api.tsx, src/pages/migrate-v6-to-v7.en.tsx
Add trigger api into the migration page because it's a breaking change.
Related to https://github.com/react-hook-form/react-hook-form/issues/4592
=> Trigger api migration

src/components/ApiGallery.module.css
I miss click severals times because only the _Read more_ text is clickable. Now the whole gallery card is clickable
=> Make the gallery card clickable

src/components/Search.tsx, src/pages/migrate-v6-to-v7.en.tsx, src/types/css.d.ts, src/types/global.d.ts, tsconfig.json
* Added tsconfig.json
* Remove @ts-ignore for missing `window.docsearch` typings
* Added global.d.ts to fix `window.docsearch` type.
* Added css.d.ts to fix css types.
* Fixed type in migration guide code example
=> Fix migrate code example & add tsconfig.js

src/data/V6/en/api.tsx
Greetings.
This PR fixes a broken link for fieldArray example in v6 docs.
=> fix broken link for v6 fieldArray example.

src/components/codeExamples/shareRef.ts, src/components/codeExamples/shareRefTs.ts
I stumbled on a small typo on https://react-hook-form.com/faqs#Howtosharerefusage 🙂
=> Fix broken ref examples

src/components/UseControllerMethods.tsx
This fixes a small typo I found while reading the docs.
Thanks for all the work on this library and it's docs!
=> Fix small typo in UseControllerMethods doc

src/components/tsPage.tsx, src/data/ts.tsx
try yourself https://react-hook-form.com/ts and tap `UseFormReturn`  is not working that's why I decided to fix it to avoid error
I simply changed different string and only one variable
So I managed to fix it if there is any mistake please let me know
=> Fixed wrong word in typescript data from `Sidemenu`

src/components/UseFormState.tsx
The code examples were referring to `useForm` instead.
=> Fix reference to `useFormState`

src/components/FormStateTable.tsx
- This PR fixes link of `ErrorMessage` in `/api/useform/formstate` page.
- to `https://react-hook-form.com/api/useformstate/errormessage`
- Now in website, no transition when clicked. (url is `https://react-hook-form.com/api/useform/formstate#errorMMessage`)
=> fix link in formState of useForm

src/components/ApiRefTable.tsx
Assignment to ref replaced with spread in `setValueAs` and `shouldUnregister` code examples in `register` docs.
=> fix `register` code example

src/components/codeExamples/testingForm.ts, src/data/en/advanced.tsx
Explaining a (what I found to be a) confusing issue regarding logged warnings about missing `act(...)` calls in unit tests with react-testing-library. 
It's what I took away from these issues: 
https://github.com/react-hook-form/react-hook-form/issues/532
https://github.com/react-hook-form/react-hook-form/issues/4231
Let me know if my interpretation was not correct or you think it should rather be placed into the FAQ section.
=> document missing act() warning behavior

src/components/codeExamples/defaultExampleTs.tsx, src/components/codeExamples/getStarted.ts
I have `"strict": true` in my `tsconfig.json`, when I pasted in the first code sample from `/get-started` the lack of types for `onSubmit` was highlighted as an error.
When looking into the code for the docs I noticed that whilst a lot of the examples weren't implicitly setting `data` in `onSubmit` as `any`, they weren't using the more thorough `SubmitHandler` type.
I also spotted that `uiLibraryHookInput` had a stray type in the plain JS example, so I removed that.
=> Improve get started example code types

src/components/codeExamples/testingForm.ts
```ts
pattern: {
value: /\S+@\S+.\S+/,
message: "Entered value does not match email format"
}
```
Should be
```ts
pattern: {
value: /\S+@\S+\.\S+/,
message: "Entered value does not match email format"
}
```
=> Fix email regex pattern

src/data/en/api.tsx
Thanks for the awesome documentation! I can't ask for more, it has proper explanation for every field, good description, CodeSandbox examples, even TypeScript. However, there was one thing that made me confused. 
This part below, the docs (https://react-hook-form.com/api/useform/getvalues) says when we supply the `firstName`, it returns `lastName` and vice versa. I think it should be consistent with the argument that we pass to the function, as reflected by the Sandbox in the same section.
This PR swaps the `.firstName` and `.lastName` in the documentation. I have cross-checked this with the sandbox in https://codesandbox.io/s/react-hook-form-v7-getvalues-2eioh and it worked as expected—`getValues(field)` will return `{ [field]: fieldValue }`.
=> docs: update `getValues` documentation

src/data/V6/en/api.tsx
I noticed that the autofocus on error doesn't work when using "custom" components like mentioned in the documentation (`submitFocusError`). However, forwarding the ref makes this work. I thought it was worth mentioning
```jsx
const Input = React.forwardRef((props, ref) => {
return <input {...props} ref={ref}></input>;
});
```
=> docs: add small note about `submitFocusError`

src/data/en/api.tsx, src/pages/migrate-v6-to-v7.en.tsx
👋 Hello and thanks for react-hook-form!
I'm knee deep in a migration from v6 to v7 and have been caught by https://github.com/react-hook-form/react-hook-form/issues/4673 which wasn't mentioned in the migration guide, so I added it here in case it helps anyone in the future.
There are a bunch of other breaking changes I've noticed in the typings (e.g. FieldArray* -> ArrayField*), but I've been kicking that can down the road for now 😄
=> Note valueAs breaking changes in migration guide

src/data/en/api.tsx
add a missing closing round bracket
=> fix a typo in the API documentation

src/data/en/api.tsx
Hello @bluebill1049, I started using react-hook-form for my side project and I am loving it.
There's a typo in the getValues api documentation.
In the docs [api/useForm/getValues](https://react-hook-form.com/api/useform/getvalues)
Check the second point under rules:
> Disabled inputs will be returned as undefined. If you want to prevent users from  _**updat**_ the input and still retain the field value, you can use readOnly or disable the entire `<fieldset />`.
I changed the word _**updat**_ to _**updating**_ according to the sentence.
Hope this is valid change.
Regards,
Rohit
=> Typo on (/api/useform/getvalues) getValues api documentation.

src/components/codeExamples/formState.ts, src/components/codeExamples/formStateTs.ts, src/components/codeExamples/formStateUseEffect.ts, src/components/codeExamples/formStateUseEffectTs.ts
There are remaining `touched` keywords which is used in v6 and replaced with `touchedFields` in v7. Also in code examples formState is being destructured to touched by `formState: { touched }`  and then trying to reach the `formState`. It is not possible after destructuring. This PR fixes those issues.
=> Fix incorrect variable names

src/components/layout.css, src/components/layout.tsx
Turns out that on focus, the button was set to `display: none` and hence, as soon as the user used to click, the button's focus state turned active and it was removed from DOM, therefore, leaving the click operation _"hanging"_.
- I tested the change in Firefox Developer Edition + Brave Browser.
- I have changed the cursor to `pointer` to increase interactivity.
- fixes #617
=> Fix Scroll Behaviour

src/components/v6/ControllerContentV6.tsx
In V6 API, controller section code examples are exported from v7 code examples. This PR fixes those imports.
=> Import v6 code examples from v6 folder

src/data/en/api.tsx
relates to #622 
I recently upgraded from `^6.15.4` to `^7.8.8` and followed [the v6 -> v7 migration guide](https://react-hook-form.com/migrate-v6-to-v7/).
The guide highlights that `setError` now accepts a config object `{ shouldFocus?: true }` rather than a boolean.
This PR updates the v7 documentation for `setError` per that change.
Current Documentation | This Change
-|-
=> fix useForm.setError "shouldFocus" documentation

src/components/useForm/UnRegister.tsx
#628 
I found this typo when going through the docs today. I created the above issue and heres the PR for it since its so small.
=> fix: minor keepError typo fix

src/data/pt/advanced.tsx
I've adjusted some typos and words but I saw that this page is completely different, maybe I can compare with live english version and update all content?
PT: [https://react-hook-form.com/pt/advanced-usage/#TestingForm](https://react-hook-form.com/pt/advanced-usage/#TestingForm)
EN: [https://react-hook-form.com/advanced-usage/#TestingForm](https://react-hook-form.com/advanced-usage/#TestingForm)
Example, look into "Set up your testing environment" section, on pt version is listed mutationobserver-shim, on english version there's no mention about this.
=> [PT-BR docs] Update Testing form docs section on advanced page

src/pages/migrate-v6-to-v7.en.tsx
There was no space between plain text and code in migration guide
https://react-hook-form.com/migrate-v6-to-v7/
=> Fix typo in migration v6 to 7 page

src/components/codeExamples/controlled.ts
In FAQ's `How to work with modal or tab forms?` 's `Custom Register` tab,
I think the parameter order of calling `handleChange` in the `lastName` field is reversed.
=> Fix typo in the modal question of FAQ

src/components/ApiErrors.tsx, src/components/ApiRefTable.tsx, src/components/UseControllerMethods.tsx
Fixes Issue #647. React.Ref is what core uses, and it is just a wrapper around React.RefObject that also includes callback refs & null:
=> React.RefObject -> React.Ref

src/data/en/api.tsx
Fix type in documentation `(errors: Object, e?: Event) => void) => void`
=> Update api.tsx [fix typo]

src/components/ResourcePage.module.css, src/components/ResourcePage.tsx, src/components/Resources.json
- Adds a case insensitive substring search bar to the resources page
- Remove the fetch to faundadb (Hi Bill 👋 , if this change becomes too much of a headache for you maintenance wise just ping me and I'll fix it to use faunadb again! 😄 )
Resolves: #656
=> Setup search filter for Resources Page

src/components/ApiRefTable.tsx
Looks like there is a space missing:
Link: https://react-hook-form.com/api/useform/register/
=> Space typo

src/components/tsPage.tsx, src/components/v6/tsPageV6.tsx
This will allow Algolia Search to better identify the TS Support Page
*FYI: I tested the change at several different screen sizes and it still formats well
=> Expand TS -> Typescript

src/components/UseWatchContent.tsx
Using `useWatch` like the previous example showed would instead provide all the values for all fields.
=> Update example to call with proper argument

src/components/codeExamples/ErrorCodeTypes.ts, src/components/codeExamples/clearError.ts, src/components/codeExamples/clearErrorTs.ts, src/components/codeExamples/errorCode.ts, src/components/codeExamples/errorMessageAdvance.ts, src/components/codeExamples/errorsMessage.ts, src/components/codeExamples/errorsMessageTs.ts, src/components/codeExamples/handleSubmitAsyncCode.ts, src/components/codeExamples/joiResolverTs.ts, src/components/codeExamples/multipleErrorCodeTs.ts, src/components/codeExamples/reactHookFormCode.ts, src/components/codeExamples/setErrorTs.ts, src/components/codeExamples/setMultipleErrorsTs.ts, src/components/codeExamples/trigger.ts, src/components/codeExamples/triggerTs.ts, src/components/codeExamples/validationResolverTs.tsx
Updated any `const { errors } = useForm();` to `const { formState: { errors } } = useForm();` in the code examples.
Did not perform the update to any of the files in the v6 directory.
=> update v7 useForm errors references

src/components/Nav.tsx, src/components/Search.module.css, src/components/Search.tsx, src/components/utils/useWindowSize.ts
Based on this userfeed back the search wasn't visible enough
The search is now open on large monitors, and automatically becomes smaller when the screen size is made smaller, also keeps the darkmode and version + language options open on large monitors.
=> Added a more visible search

src/data/en/faq.tsx
Proxy has been removed from codebase, so react native will share the same perf enhancement as web. Regardless, Hermes v0.7+ supports Proxy by default.
=> Remove outdated RN Hermes polyfill advice

src/components/codeExamples/errorsMessage.ts, src/components/codeExamples/errorsMessageTs.ts
Assume I made a mistake, because the examples are inside a string literal.
=> docs: fixed missing render props in multiple ErrorMessage examples

src/data/pt/advanced.tsx
Just a little translate fix to ptBr doc
=> docs: Fix translation of topic titles

src/data/en/api.tsx
"It" is ambiguous in this context.  Replacing with the explicit field value being discussed (`name`)
=> [docs] `register()` wording clarity

src/pages/about-us.tsx
The url was wrong for https://github.com/barrymay on the about us page.
=> fix: about-us barrymay url

src/components/codeExamples/resetFieldCode.ts
In the code example of [resetField](https://react-hook-form.com/api/useform/resetfield), the definition of handleClick was missing, so I added it.
Fixed to match the code in [CDB](https://codesandbox.io/s/resetfield-with-options-iw4wd).
=> fix: added the definition of handleClick

src/data/en/api.tsx
Added space to prevent words mix
Prev
Now
=> Fix words mix

src/components/useForm/GetFieldState.tsx
Seems like this was copied from the previous item (`invalid`).
=> Fix incorrect property name for fieldState.error

src/components/codeExamples/errorsMessageTs.ts
Due to a lack of colons, the following error has been fixed.
```
Failed to compile.
SyntaxError: /Users/program/src/components/pages/SignUp.js: Unexpected token, expected "," (7:17)
5 | export default function App() {
6 |   const { register, formState: { errors }, handleSubmit } = useForm({
>  7 |     criteriaMode "all"
|                  ^
8 |   });
9 |   const onSubmit = data => console.log(data);
10 |
```
=> Update:missing colon

src/data/en/advanced.tsx
After hours of head-scratching and trying to figure out why my forms are not performing the way they should, and spending hours on optimizations (ie. memoization,  consolidating input fields),  I came to find out that the source of my bottleneck was RHF Devtools.
This PR adds this note just below the FormProvider performance description in Advanced Usage,  in hopes it will save others time, headaches, engineering hours & money that is usually the cost of doing performance optimizations.
=> Note about FormProvider performance when using RHF Devtools

src/data/en/api.tsx
Explicitly state that calling `onChange` with `undefined` will clear the named field when using `useController`.
This is a useful operation, since some types of form inputs, such as number input, can be cleared in a way which means something different than any allowable value.
=> Add description of undefined onChange to useController documentation

src/data/en/api.tsx, src/data/generic.tsx
I would like to add default values for the `options` object that can be passed to the `reset` function as a parameter. 
Today, I was trying to find out what are the default values for all the possible atributes in the `options` objects and it took me a while to find it in the source code. 
I believe that it can be helpful to include default values in the docs as well.
=> Docs: Add default values to reset options

src/components/Header.module.css
closes #748 
Button width change in light mode is causing the word "React Native" to break. 
Because of the "React Native" button being a border box element, changing border from `0` to `1px` affecting its width. Increasing width of button will also fix it but I thought of finding out css rule causing the issue. 
```css
.toggleGroup > button:last-child {
border-left: 0;
.
.
.
}
```
```css
.light button {
border: 1px solid transparent !important;
.
.
.
}
```
```css
.toggleGroup > button:last-child {
border-left: 0 !important;
.
.
.
}
```
The fix is about same rule  being applied in both light and dark mode.
=> Enhancement: fix of button togglegroup alignment in lightmode

src/components/useForm/GetFieldState.tsx
Make information about the need to subscribe to the relevant state information clearer, include a note for Typescript users who may not want unused declarations.
=> Add some details to getFieldState subscription documentation

src/components/UseFormState.tsx
mention that control is optional in useFormState if you're using FormContext.
=> mention that control is optional in useFormState

src/components/logic/generateCode.ts
- Fix #762. I hope someone else doesn't get confused when they use the Bulder playground.
- Before this PR:
- After: this PR
=> fix optional field generate incorrect code 🐛

src/components/ApiGallery.tsx
There is a grammatical error in the English ApiGallery file.
=> Fix EN grammatical error in ApiGallery

src/components/codeExamples/register.ts
The example didn't work properly in TS as `category` was missing from `defaultValues`
`
=> Update `register` example

src/components/codeExamples/joiResolver.tsx, src/components/codeExamples/v6/joiResolver.tsx, src/components/codeExamples/v6/zodResolver.ts, src/components/codeExamples/zodResolver.ts
I noticed that there were a couple of code snippets in the docs that were missing the closing `)` in the `onSubmit` handler. So I've gone ahead and made a quick PR to fix them.
=> fix (docs): add missing closing parentheses for joi & zod code snippets

src/components/UseControllerMethods.tsx
Tiny PR to fix broken link on `useController` page
=> Fix:  typo in `setValue` link on `useController` page

src/components/codeExamples/submitReset.ts
Hello!
I was following along with the docs (excellent, btw!) and noticed a missing destructure in the `Submit with Reset` code example at https://react-hook-form.com/api/useform/reset
Using the codesandbox feature, and copy-pasting ***this exact code***, yields an error consistent with my local environment:
Using the codesandbox feature and not changing the initial code that loads in the sandbox, you'll notice the additional destructure present https://codesandbox.io/s/react-hook-form-handlesubmit-with-reset-xu1zu
If I am missing some quirk of the architecture or your process - feel free to close
=> docs(example): add destructure on useForm example

src/data/en/api.tsx
I think that `useForm()` accepts only **one** optional argument and the things listed in the example are **its properties**.
=> useForm API: Improve correctness of JS terminology

src/components/GetStartedPage.tsx
This PR applied the following style fix in the [Schema Validation](https://react-hook-form.com/get-started#SchemaValidation) section:
Before:
After:
=> fix: code snippet style on light mode

src/components/codeExamples/getStarted.ts
I guess the code example in section "Integrating with global state" was supposed to use "input" (all lowercase) instead of "Input" component. Because there is no "Input" component being defined.
=> fix: uppercase "Input" instead of "input"

src/components/v6/ApiWatchV6.tsx
The v6 documentation currently shows an example for a callback version of watch, which is only available in v7:
```
// Callback version of watch.  It's your responsibility to unsubscribe when done.
React.useEffect(() => {
const subscription = watch((value, { name, type }) => console.log(value, name, type));
return () => subscription.unsubscribe();
}, [watch]);
```
https://react-hook-form.com/v6/api#watch
This seems to have happened because the imports for the code examples point to the latest examples directory, rather than the v6/ directory.
The same issue was mentioned by another user [here](https://github.com/react-hook-form/react-hook-form/issues/1905#issuecomment-928716607)
=> Fix v6 watch API code example

src/components/codeExamples/useFieldArrayPreview.ts
Looks like it's not actually supported
=> remove `defaultValues` from `useFieldArray` docs

src/styles/typography.module.css
fix #811
The word Rules is now black in light mode, as shown in the image
=> Rules text turns black in light mode. fix #811 

src/components/useForm/GetFieldState.tsx
Page Link https://react-hook-form.com/api/useform/getfieldstate
Here's the screenshot
=> fix: missing space between words

src/components/UseWatchContent.tsx, src/data/en/getStarted.tsx
=> Fix typo on useWatch and Get Started pages

src/components/Nav.module.css
=> Fix light mode navbar font

src/components/useForm/GetFieldState.tsx
Change `getFieldState` type from `object` to `(name: string, formState?: Object) => ({isDirty, isTouched, invalid, error})` to make API more clear.
[getFieldState API](https://react-hook-form-website-git-fork-abdmmar-abdmm-ce6aed-hook-form.vercel.app/api/useform/getfieldstate/)
=> fix: add `getFieldState` types

src/data/en/api.tsx
[Documentation link](https://react-hook-form.com/api/useform/register/#example:~:text=How%20to%20work%20with%20innerRef%2C%20inputRef%3F)
I added the name prop. 
I didn't add a name prop to my code like a document at the first time.
My code didn't validate well when the mode was `all`, `onChange`, and `onBulr`. 
I found the name prop was the cause. 
I think it would be better to add a name prop to the document.
=> include missing prop to forwardRef example

README.md
Change "Become a contributor" link from `react-hook-form/react-hook-form` repository to `react-hook-form/documentation` 
repository
=> docs: fix "become a contributor" link

src/components/layout.tsx, src/components/logic/getEditLink.tsx
Specifically targeted only data sources under V6 and V5 folders for legacy-docs.
Points to note:
1. Modified source prefix to point to `V6-V5` branch instead of `master` as legacy docs are served from that branch.
2. Noticed there are two versions of `/advanced-usage`. For now handled the links as they are shown in docs.
- `V7, *` https://github.com/react-hook-form/documentation/blob/v6-v5/src/data/en/advanced.tsx
- `V6, en` https://github.com/react-hook-form/documentation/blob/v6-v5/src/data/V6/en/advanced.tsx
=> fix: edit links for api and advanced pages

src/components/codeExamples/useFieldArray.ts
The code example referenced in the [`useFieldArray` documentation page](https://react-hook-form.com/api/usefieldarray) is missing to define the `remove` that is referenced below (see screenshot).
=> FIX: Add missing reference to `remove` in the `useFieldArray` example

gatsby-browser.js, src/components/Toggle.tsx, with-little-state-machine.js
Start using "window.localStorage" for little state machine in order to keep theme settings on multiple tabs.
Related issue: https://github.com/react-hook-form/documentation/issues/838
=> #838 Apply storage type "window.localStorage" on little state machine

src/components/DevTools.tsx
Added the `-D` flag to the installation command so users can streamline copy-pasting the command without needing to remember to add the flag when running the command.
=> Update DevTools.tsx | Add -D flag to install cmd

src/components/BuilderPage.tsx
V7
- Go to [Form Builder](https://react-hook-form.com/form-builder) page with the default example field
- Click "Edit" button on one of the items (except the first item) in the list Layout section
- Click "Delete All" button at the bottom of the Layout section
- Click "Update" button in the Input Creator section
- Page is blank and unusable 
When updating the form input item and the input list is empty, add the updated item to the list
- Google Chrome Version 106.0.5249.119
- Brave Version 1.44.112 Chromium: 106.0.5249.119
```
{
formData: [
null, // root cause
{
"name": "Last name",
"type": "text",
"toggle": true,
"required": true,
"max": "",
"min": "",
"maxLength": "100",
"pattern": ""
}
],
setting: {
"lightMode": false,
"isFocusOnSearch": false
}
}
```
=> fix(form-builder): updating edited input on an empty list results in a blank error page

src/components/BuilderPage.tsx, src/components/ClipBoard.tsx, src/components/CodeArea.module.css, src/components/CodeArea.tsx, src/components/DevTools.tsx, src/components/GetStarted.tsx, src/components/GetStartedPage.tsx, src/data/en/faq.tsx, src/data/generic.tsx
We are currently opening an `alert` to let you know that the code has been copied. My proposal is to improve the user experience by informing on the button itself that the code is already copied in its transfer area. If this change makes sense, we create this action for the others copy buttons.
=> Proposal change to the copied code

src/components/UseForm.tsx
Fix for ESLint error - `li` element had `kay` property instead of `key`
=> fix typo kay->key for list

src/components/BuilderPage.tsx
I add a required validate on input **radio** and **select** to solve this issue: https://github.com/react-hook-form/documentation/issues/834. 
I think we don't have a bug on this page if you add an `Options` on the page build it will generate a code for you, but if you don't add the `Options` they don't create a code for you. My proposal is required the options field. Looks good for you?
=> Enhancement: Input radio validade on page builder

src/components/ApiGallery.tsx
Today on the main site(https://react-hook-form.com/) we have a bug when the user access the API documentation and change the **version to 6 or 5**:
This bug occurs because we don't have a page folder to v6 and v5 api: 
My proposal is to redirect the user to legacy documentation when they change the version v6(https://legacy.react-hook-form.com/v6/api) and v5(https://legacy.react-hook-form.com/v5/api) documentation. On the legacy we have a page for this versions:
Recording the issue fix. 
Look good for you? What do you think?
=> Fix: Add redirect to legacy api doc

src/components/logic/getEditLink.tsx
Hi, I'm here again! 😊
I proposal a logic to redirect to a correct page when user click on edit button on API pages, today they redirect to api.tsx generic page. (https://github.com/react-hook-form/documentation/edit/master/src/data/en/api.tsx)
My proposal is to redirect to a correct github page with user access on the doc. 
Obs: I create a logic to remove the last "/" if the user access urls to end with ** /**, this break a redirect link to github: 
Example:
I think this PR solve this issue: https://github.com/react-hook-form/documentation/issues/831
=> Proposal: redirect button "edit on github" to a correct page

src/data/en/getStarted.tsx
Fixed a small typo in 'Design and philosophy' section of 'Get Started' page
=> fix typo in design and philosophy section

src/components/ApiRefTable.tsx
- Update description of "valueAsNumber" option to be more clear it's specially targeting `<input type="number" />` to avoid confusion.
Reference: https://github.com/react-hook-form/react-hook-form/pull/9299
=> Update description of "valueAsNumber" option

src/components/codeExamples/testingForm.ts, src/data/en/advanced.tsx
Hi!
[eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library) author here. I've found many people following the wrong advice from the `react-hook-form` docs about how to fix the React Testing Library `act()` warning.
I've updated the docs and the examples, so it's on the same page as the official Testing Library best practices.
=> docs(advanced): Improve the Testing Form section

src/components/Nav.tsx
- Quick fix on the github repository link
=> Updating github repo link

src/data/en/api.tsx
This is simple and clear. The control prop is not given to useWatch.
=> Add forgotten control in code example

src/components/BuilderPage.tsx
The BuilderPage had an issue when we create new form fields the code doesn't generates for the validation and type also gets as "undefined" when we create 2 fields in a row.
In the below example I tried to create two field with basic and same configuration without and validation. The first one with the field name "test1" got successful and showed up as per the inputs but for the second input with field name "test2" was created but with undefined as the type of the input as shown in the below picture
=> Fixed undefined error on builder

src/components/UseForm.tsx
UseForm.tsx uses h5 for prop parameters, and includes a special table for some of them. But the styling on prop names within the table is different than the styling for others. This resulted in my initial confusion about which fields were properties of useForm, and if there was some other detail related to prop resetOptions.
This PR removes the table wrapping those properties and aligns the prop names with the same styling h5>code as the others. New tables are used for each prop to show the description on the left and a link to the CodeSandBox on the right.
Anomalies:
- The prop name is now above the description, as with other props, and is followed by a light-blue border-bottom. Unfortunately after the border bottom for these labels, the div>table for the description is slighly further …
=> Standardize useForm prop formatting

src/components/BuilderPage.tsx
Validation checkbox issue whenever used the validation popup isn't hidden by default from the user.
Test performed:
The following was submitted for the first time
and after clicking on create the validation popup (which contains required, min, max fields) continued to show up while the checkbox was unchecked
Modified: When clicking on create the state of popup was changed to make sure the popup is hidden
=> Fixed issue with validation checkbox

src/components/codeExamples/getStarted.ts
- The ts code example in the section `Integrating with UI libraries`  in the get started page is missing the `IFormInput` interface.
- But the codeSandbox includes the `IFormInput` interface, so this pull request adds the same.
- It is being used  in the ts example code already, only the definition is missing.
https://github.com/react-hook-form/documentation/blob/a9d51013cd265cbbb7d40a53a6c4a09b97e04c67/src/components/codeExamples/getStarted.ts#L194
=> Fix: `cannot find IFormInput name` error in  code examples.

src/components/ApiWatch.tsx, src/components/UseWatchContent.tsx
This is for the legacy docs. I found a type while checking `useWatch` documentation. Fixing it here.
=> Fixed typos in watch pages

.github/workflows/lighthouse.yml, .lighthouserc.js
Noticed last 2 commits failed on lighthouse check.
Seems like a simple update to use latest action version + nodejs 16
Related to https://github.com/GoogleChrome/lighthouse-ci/issues/842
=> fixing lighthouse for commits

src/components/ApiRefTable.tsx, src/components/UseForm.tsx, src/components/useForm/UnRegister.tsx, src/data/en/api.tsx
I've noticed that the phrase `build-in` is used throughout the code, however the correct spelling is [built-in](https://www.merriam-webster.com/thesaurus/built-in). This PR replaces all the occurrences of build-in with built-in.
=> Documentation: Fix the spelling of 'built-in'

src/data/resources.tsx
I've updated my articles from the resources section to use the version 7 of React Hook Form, so I've moved them into the v7 section. I've also added one other article about working with multi-step forms, which might be useful to the readers.
=> Resources: Use updated article versions

src/components/UseForm.tsx, src/components/ValidationResolver.tsx, src/data/en/api.tsx
Update the documentation for the [useForm](https://react-hook-form.com/api/useform/) page:
- Add missing `tbody` tags inside tables to fix invalid DOM nesting warnings.
- Add consistent capitalisation of list items.
- Add a few missing `p` wrappers for the text.
- Misc grammar and spelling fixes, plus some improved readability.
=> Documentation: useForm fixes and updates

src/components/UseWatchContent.tsx
This PR updates the documentation of the `useWatch` hook. The **Return**  section was confusing as it implied devs could pass a `string` as an argument to `useWatch` to get a field's value. Instead, they have to pass an object with a `name` property.
Closes #927
=> fix: update useWatch hook documentation

src/components/codeExamples/reactNativeController.ts
While looking at the documentation of React Hook Form for React Native, the example code gave an error because of a not existing style. 
I removed this and replaced it with a placeholder, now the code works directly.
=> Replaced not existing style attribute for placeholder

src/components/codeExamples/zodResolver.ts, src/components/codeExamples/zodResolverTs.ts
Hi,
in the zod resolver examples on the following page https://react-hook-form.com/api/useform/ it's not possible to run the code because the "age" field goes in error with the following message: `Expected number, received string`.
To resolve the error I added the `{ valueAsNumber: true }` in the age input.
There is the same error in the codesanbox examples, also in these examples, there is another error, the name type is a number instead a string. Is there a way to fix them? If you let me know I can do that.
Thanks
=> Example in zod validation resolver doesn't work

src/components/Nav.tsx
`FROM` -> `FORM` in Beekai Form Builder navigation item.
=> Fix typo in navigation

src/components/Nav.module.css
Light theme navbar has a global style none applied when it should only be done if screen size is 1024px +
=> fix: light background on mobile menu

src/data/ts.tsx
"export" word in docs was written twice
=> fix: typo in TS Support FieldArrayWithId

src/components/codeExamples/useFormState.ts
- related issue: #951 
- added `Child` component in the `useFormState` example to demonstrate the suppression of the re-rendering of the `App` component.
- The corresponding [CodeSandbox](https://codesandbox.io/s/useformstate-75xly) should also be fixed. (I forked the original one to create a fixed version [here](https://codesandbox.io/s/useformstate-forked-1whjlm?file=/src/App.js) )
=> Fix useFormState code example

src/pages/api/[[...route]].ts
Adds a catch all api route for anything under "/api"
https://nextjs.org/docs/pages/building-your-application/routing/api-routes#optional-catch-all-api-routes
TODO: move to 301 in the future. Right now keeping at 307 since I had issues in testing if I messed up since it would have a wrong redirect.
=> fix: adding redirect logic from api pages

src/components/Search.tsx, src/types/global.d.ts
Upgrading to https://docsearch.algolia.com/docs/DocSearch-v3 would be more ideal than this fix but it will prevent this script from crashing the page.
Tested by removing docsearch script from Head and loading the page.
Before, it would crash the page. Now, search is disabled instead.
=> fix: if docsearch is not loading, don't crash page

src/content/get-started.mdx
Fixed the the typo in the npm install instruction from 'yupcopy ' to 'yup'. This fix ensures accurate installation of yup package.
=> Fix typo in npm install command.

package.json
The start script referenced a nonexistent `develop` script. Now updated to `dev` script.
=> fix: make start script reference dev script

src/components/DevTools.tsx
Oversight on my part.
Devtools was working in local development because process.env === "DEVELOPMENT"
When deploying to prod, DevTools became a no-op and does not render. https://github.com/react-hook-form/devtools/blob/master/rollup/writeCjsEntryFile.js
This changes the import path to use the development bundle and still appear in prod. 
This change got lost in trying to use the dynamic import as suggested by devtools repo for it to work in nextjs.
* npm run dev - Worked as expected in development
* npm run build && npm run start - Build + start mimicks prod behaviour. Worked when importing the development bundle since it doesn't become a no-op
=> fix: devtools dependency stripped out in prod

src/content/get-started.mdx
Fix TS typo in `src/content/get-started.mdx`
_before_
```ts
firstName: String
```
_after_
```
firstName: string
```
=> fix: update typo in get started example

src/content/advanced-usage.mdx
#1004 
This PR fixes paths for "FormContext" and "FormProvider".
I assumed `/docs#useformcontext` for an expected behavior[^hash] on #1004. But in reality, I adopted `/docs/useformcontext`. Because the linked URL `/docs/useformcontext` in the below line can already move to [useFormContext](https://react-hook-form.com/docs/useformcontext) in API doc.
https://github.com/react-hook-form/documentation/blob/e7cdd0fb68f61667beaca25a4aab5fea88a59178/src/content/advanced-usage.mdx#L308
[^hash]: > Linked URL is `/docs#useFormContext` such as a current link of FormProvider.
=> Fix some linked URLs on the "Advanced Usage" page

src/content/docs/useform.mdx
Setting default props asynchronously requires a function to return a promise, not just the promise. See [these lines](https://github.com/react-hook-form/react-hook-form/blob/011fad503cc8d4543892f8e847b9bd58c1d9400f/src/types/form.ts#L98-L108) for evidence. This is documented incorrectly but is fixed by this pull request.
_Note: [The async defaultValues function includes a parameter](https://github.com/react-hook-form/react-hook-form/blob/011fad503cc8d4543892f8e847b9bd58c1d9400f/src/types/form.ts#L99C3-L99C21) [which appears to never be used](https://github.com/react-hook-form/react-hook-form/blob/011fad503cc8d4543892f8e847b9bd58c1d9400f/src/logic/createFormControl.ts#L1262). So it would be misleading to include that parameter in the type documentation._
=> fix: correct useForm defaultValues type documentation

src/content/get-started.mdx
This optional chaining is unnecessary because `errors.mail` at the beginning of the line ensures `errors.mail` is not nullish.
=> Remove unnecessary optional chaining

src/content/faqs.mdx
**Description:**
This PR adds an enhancement to the React Hook Form documentation by demonstrating how to share a ref using the `useImperativeHandle` hook. The shared ref is used to clear the input value when a user clicks on a "clear" button.
**Changes Made:**
- Added a code snippet in both TypeScript and JavaScript that showcases the usage of `useImperativeHandle` to share a ref.
- Created a functional component (`App`) that utilizes `useForm` from `react-hook-form`.
- Created a `ref` using `useRef` to reference the input element.
- Defined an `onSubmit` function to handle the form submission.
- Extracted the `ref` and other properties from the `register` function for the "firstName" input field.
- Implemented an `onClick` function that clears the value of the input element when the …
=> use `useImperativeHandle` to share Refs

src/content/advanced-usage.mdx
"Transform and Parse" did not point to the right place
=> Update advanced-usage.mdx wrong link reference

src/components/ApiRefTable.tsx, src/components/UseFieldArrayContent.tsx, src/content/docs/useform/watch.mdx
This commit addresses a typo in the documentation found in the following files:
1) ApiRefTable.tsx
2) useForm/watch.mdx
3) UseFieldArrayContent.tsx
The word 'recommend' was replaced with 'recommended' in 'it's recommended' for consistency and accuracy throughout the documentation. This resolves the issue raised in #1032.
=> docs: fix typo, replace 'recommend' with 'recommended' in documentation 

src/components/Menu/MenuLinks.ts
The Typescript Support page's Menu bar was missing navigation for `FieldPathByValue`.
I have added the missing navigation entry to improve documentation's usability.
- A new menu item for `FieldPathByValue` has been inserted into the appropriate location in the Menu bar.
- Ensured the navigation link correctly redirects to the `FieldPathByValue` section.
This update ensures that users can navigate more efficiently and find the information they need regarding `FieldPathByValue`.
Please review the changes and let me know if any further adjustments are needed.
- MenuLinks.ts
- tsLinks: https://github.com/react-hook-form/documentation/blob/master/src/components/Menu/MenuLinks.ts#L164
- ts.mdx
- FieldPathByValue: https://github.com/react-hook-form/documentation/blob/master/src/content/ts.mdx#L4 …
=> docs(MenuLinks): Add Navigation for FieldPathByValue in Typescript Support Page Menu

src/content/advanced-usage.mdx
The link was originally rendered in a code block. It now renders as an actual link
=> Correctly link to lodash get documentation

src/content/docs/useform.mdx
Hello, it might be helpful to clarify how `values` and `defaultValues` work when both props are used with the `useForm` hook. This behaviour seems to have tripped up [another user before](https://github.com/react-hook-form/react-hook-form/issues/10954).
I observed the behaviour when using `defaultData` to store default values and `values` for storing the latest form values that were previously submitted. When trying to reset the form via `reset` or resetting the field via `resetField` `values` would be used as default values instead of `defaultValues` unless `resetOptions: { keepDefaultValues: true }` was used.
Cheers
=> Add section on behaviour of values prop in combination with defaultValues prop

src/content/docs/useform/handlesubmit.mdx
Based on RHF types
UseFormHandleSubmit: https://github.com/react-hook-form/react-hook-form/blob/master/src/types/form.ts#L626
SubmitErrorHandler: https://github.com/react-hook-form/react-hook-form/blob/master/src/types/form.ts#L81
handleSubmit method type should be descripted as follows:
handleSubmit: (
(data: Object, e?: Event) => Promise<void>,
(errors: Object, e?: Event) => Promise<void>
) => Promise<void>
=> Fix handleSubmit type documentation.

src/components/Menu/MenuLinks.ts
Menu links and Content have different order.
So, re-order `getStartedLinks` in `MenuLinks.ts`.
Menu - **Integrating with services** -> **Handle errors**
Content - **Handle errors** -> **Integrating with services**
- MenuLinks:
- Handle errors: https://github.com/react-hook-form/documentation/blob/master/src/components/Menu/MenuLinks.ts#L280-L283
- Integrating with services: https://github.com/react-hook-form/documentation/blob/master/src/components/Menu/MenuLinks.ts#L276-L279
- Content
- Handle errors: https://github.com/react-hook-form/documentation/blob/master/src/content/get-started.mdx#L602
- Integrating with services: https://github.com/react-hook-form/documentation/blob/master/src/content/get-started.mdx#L639
=> fix(MenuLinks): reorder getStartedLinks

src/components/Nav.module.css
Fixes #1091
Now X icon is visible on both light and dark mode on mobile version.
=> style(nav): fix X icon visibility issue

src/components/Menu/Menu.tsx
This PR implements an enhanced side menu component that automatically highlights the current section as users scroll through the page. The menu now provides visual feedback for navigation, improving the overall user experience in our single-page documentation layout.
- Implemented scroll-based active section detection
- Added visual highlighting for both parent and child menu items
- Introduced smooth scrolling behavior when clicking menu items
- Updated styling to support the new interactive features
- Uses `useEffect` and scroll event listener to track the current section
- Calculates section positions dynamically to handle content updates
- Implements a `100px` offset for better UX when transitioning between sections
- Handles both top-level and nested menu items
##Execution Video …
=> Added scroll based menu highlight feature

src/content/docs/useform.mdx
Related to https://github.com/react-hook-form/react-hook-form/issues/12463.
Adds a new section in useForm page informing about the future problems of adding the whole `useForm` return to the dependencies list of a `useEffect`
=> feat(useForm): add “`useForm` return and `useEffect` dependencies”

.gitignore, CONTRIBUTING.md, README.md, package.json
Part of #1098
`yarn` occurrences in the project have been replaced with the relative `pnpm` counterparts.
=> chore: replace `yarn` scripts with `pnpm` scripts

.github/workflows/ci.yml, package.json, src/components/BuilderPage.tsx, src/components/mdx/theme.ts
Part of #1098.
> [!NOTE]
> ~~Based upon #1102 (I marked this PR as draft, will rebase and make it ready for review after #1102 is merged)~~.
- fixed typescript errors
- ~~added `typecheck` script to `ci.yml` checks~~
- added `typecheck:ci` script to `ci.yml` checks
I'm not using directly `typecheck` script because `src/pages/[...slug].tsx`  file requires types from `contentlayer/generated` which are available only after `next build`.
To resolve this issue I created a new `typecheck:ci` script that runs `next build --no-lint` before `tsc --noEmit`
Let me know if you want that this explanation should be added to `CONTRIBUTING.md` for future reference.
=> refactor: fix typecheck errors and add script execution to CI

.eslintrc.js, src/components/Admonition.tsx, src/components/ApiGallery.tsx, src/components/BuilderPage.tsx, src/components/DevTools.tsx, src/components/Form.tsx, src/components/FormFields.tsx, src/components/HomePage.tsx, src/components/IsolateRender.tsx, src/components/Search.tsx, src/components/SortableContainer.tsx, src/components/TabGroup.tsx, src/components/TypeText.tsx, src/components/logic/generateCode.ts, src/components/logic/getEditLink.tsx, src/components/mdx/code.tsx, src/components/mdx/pre.tsx, src/data/generic.tsx, src/pages/[...slug].tsx, src/pages/about-us.tsx, src/pages/api/[[...route]].ts, src/state/formData.ts, src/types/little-state-machine.d.ts, tsconfig.json
Part of #1098.
Enabled following ts `compilerOptions`:
- `strict`
- `noImplicitAny`
- `noImplicitThis`
- `noUnusedLocals`
- `noUnusedParameters`
- `noImplicitReturns`
- `noFallthroughCasesInSwitch`
Most of the changes involves only type related expect for few exceptions:
1. `src/components/FormFields.tsx` I added a `getNumericValidationFor` to help creating `register#RegisterOptions` 
2. Removed few spreads when rendering JSX components. Plain property should be enough
=> refactor: enable typescript `strict` mode

.eslintrc.js, next-env.d.ts, next.config.ts, package.json, pnpm-lock.yaml, src/components/FormFields.tsx, src/components/mdx/code.tsx
Part of #1098.
I changed the order of the tasks.
Getting `eslint@9` will be easier if we are using `next@15`.
I updated all next js dependencies using the [official codemod](https://nextjs.org/docs/app/building-your-application/upgrading/version-15).
When trying out the site I encountered a few non-blocking errors related to `key` prop management
in the following files:
- `src/components/FormFields.tsx` (duplicate / missing `key` prop)
- `src/components/mdx/code.tsx` (`key` prop should not be passed via spread operator)
----
I navigated a few pages and test the form builder running the site via `pnpm run build` and then `pnpm run start`.
> [!NOTE]
> React has been update to `v18.3.1`.
=> feat(deps): update next to v15.1

src/components/BuilderPage.module.css, src/components/BuilderPage.tsx, src/components/Popup.module.css
Close #1096 
I encountered the above linked issue when using the form builder in light mode.
To fix the issue I used `var(--color-background)` as background of the form-builder element
and `var(--text-color)` as border-color for the icons
<details><summary>This is the result:</summary>
<p>
</p>
</details>
=> fix(BuilderPage): use css variables for background and icon border color

src/components/Menu/SideMenu.module.css
Prevents code icon in side menu item to be shrunk by a line-overflowing text.
Before:
After:
=> fix(SideMenu): minor CSS tweak

src/content/advanced-usage.mdx
Hi, this PR corrects minor roughness in snippets from ["Advanced usage"](https://react-hook-form.com/advanced-usage)
=> cleanup snippets in advanced-usage

src/content/docs/useform/handlesubmit.mdx, src/content/ts.mdx
- I added `SubmitErrorHandler` type to `ts.mdx`.
- In the synchronous example of `handleSubmit`, `onError` was only set for the JavaScript example, so I added it to the TypeScript example as well.  
- Removed unused variables in the asynchronous example.  
I wanted to add a sandbox example for `SubmitErrorHandler` type, but I was unsure if I could include my personal sandbox link. How can I add a sandbox link?
=> docs: Add `SubmitErrorHandler` type to `ts.mdx`

src/components/Admonition.module.css
Addressing: https://github.com/react-hook-form/documentation/issues/1124
Before:
After:
=> Fix: admonition svg color in light mode

src/data/api.tsx
Very minor, just removing an extra instance of `only`.
=> remove superfluous word

src/content/docs/usecontroller/controller.mdx, src/content/docs/useform.mdx, src/content/docs/useform/clearerrors.mdx, src/content/docs/useform/control.mdx, src/content/docs/useform/getvalues.mdx, src/content/docs/useform/handlesubmit.mdx, src/content/docs/useform/reset.mdx, src/content/docs/useform/seterror.mdx, src/content/docs/useform/setfocus.mdx, src/content/docs/useform/setvalue.mdx, src/content/docs/useform/subscribe.mdx, src/content/docs/useform/trigger.mdx, src/content/docs/useform/unregister.mdx, src/content/docs/useform/watch.mdx, src/content/docs/useformstate/errormessage.mdx, src/content/docs/usewatch.mdx, src/content/faqs.mdx, src/content/get-started.mdx, src/content/ts.mdx
- Updated resolver examples to avoid unnecessary generics now that the resolvers all support inference
- Changed some codeblocks to `lang=tsx` to slightly improve syntax highlighting
Before:
After:
=> Update resolver examples to use inference. Improve highlighting.

src/components/ApiGallery.tsx, src/components/Menu/MenuLinks.ts, src/content/docs/uselens.mdx
Create docs for https://github.com/react-hook-form/lenses package
close #1154
=> Lenses docs

src/content/docs/useform/handlesubmit.mdx
In this `tsx` code block we define `onError`, but we never pass it to the `handleSubmit` function.
In the `jsx` code block we pass the `onError` properly.
=> Add `onError` to TypeScript code block `handleSubmit` function

src/content/docs/useform/watch.mdx
This PR fixes the watch() function documentation, which previously listed incorrect overloads.
**Before**
```ts
watch(name: string, defaultValue?): unknown
watch(names: string[], defaultValue?): {[key:string]: unknown}
watch(): {[key:string]: unknown}
```
**After**
```ts
watch(name: string, defaultValue?: unknown): unknown
watch(names: string[], defaultValue?: {[key:string]: unknown}): unknown[]
watch(): {[key:string]: unknown}
```
=> Fix watch overload types
